{{ config(
    materialized = 'incremental',
    unique_key = 'ACCOUNT_NO',
    incremental_strategy = 'merge'
) }}

SELECT 

TRY_CAST(ACCOUNTNO AS INT) AS ACCOUNT_NO,
RECORDNO AS RECORD_NO,
CATEGORYKEY AS CATEGORY_KEY,
CLOSETOACCTKEY AS CLOSE_TO_ACCTKEY,
ALTERNATIVEACCOUNT AS ALTERNATIVE_ACCOUNT,

TRIM(TITLE) AS TITLE,
COALESCE(CLOSINGACCOUNTTITLE, 'UNKNOWN') AS CLOSING_ACCOUNT_TITLE,
COALESCE(CATEGORY, 'UNKNOWN') AS CATEGORY,

ACCOUNTTYPE AS ACCOUNT_TYPE,
STATUS,
CLOSINGTYPE AS CLOSING_TYPE,
NORMALBALANCE AS NORMAL_BALANCE,
TAXABLE,
ENABLE_GLMATCHING,
SUBLEDGERCONTROLON AS SUBLEDGER_CONTROL_ON,

REQUIREEMPLOYEE AS REQUIRE_EMPLOYEE,
REQUIRECUSTOMER AS REQUIRE_CUSTOMER,
REQUIREITEM AS REQUIRE_ITEM,
REQUIRELOC AS REQUIRE_LOC,
REQUIREVENDOR AS REQUIRE_VENDOR,
REQUIREDEPT AS REQUIRE_DEPT,
REQUIRECLASS AS REQUIRE_CLASS,
REQUIREWAREHOUSE AS REQUIRE_WAREHOUSE,
REQUIREGLDIMREVENUE_CENTER AS REQUIREGL_DIM_REVENUE_CENTER,
REQUIREPROJECT AS REQUIRE_PROJECT,

CAST(WHENCREATED AS DATE) AS CREATED_DATE,
CREATEDBY,
CREATEDBYLOGINID AS CREATED_BY_LOGIN_ID,
MODIFIEDBY AS MODIFIED_BY,
MODIFIEDBYLOGINID AS MODIFIED_BY_LOGIN_ID,

TRIM(RECORD_URL) AS RECORD_URL


  -- Audit
    _FIVETRAN_DELETED AS IS_DELETED,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE

FROM {{ source('spotless_sage', 'GL_ACCOUNT') }}


{% endif %}