{{ config(
    materialized = 'incremental',
    unique_key = 'ITEM_ID',
    incremental_strategy = 'merge'
) }}

SELECT
    -- Primary Key
    TRIM(ITEMID) AS ITEM_ID,

    -- Core Identifiers
    TRY_CAST(RECORDNO AS INT) AS RECORD_NO,
    TRIM(NAME) AS ITEM_NAME,
    TRIM(ITEMTYPE) AS ITEM_TYPE,
    TRIM(PRODUCTTYPE) AS PRODUCT_TYPE,
    TRIM(PRODUCTLINEID) AS PRODUCT_LINE_ID,
    TRY_CAST(PRODUCTLINERECORDNO AS INT) AS PRODUCT_LINE_RECORD_NO,
    TRIM(STATUS) AS STATUS,

    -- Flags
    CAST(ALLOW_BACKORDER AS BOOLEAN) AS ALLOW_BACKORDER,
    CAST(ALLOWMULTIPLETAXGRPS AS BOOLEAN) AS ALLOW_MULTIPLE_TAX_GROUPS,
    CAST(AUTOPRINTLABEL AS BOOLEAN) AS AUTO_PRINT_LABEL,
    CAST(BUYTOORDER AS BOOLEAN) AS BUY_TO_ORDER,
    CAST(CNDEFAULTBUNDLE AS BOOLEAN) AS CN_DEFAULT_BUNDLE,
    CAST(COMPLIANTITEM AS BOOLEAN) AS COMPLIANT_ITEM,
    CAST(COMPUTEFORSHORTTERM AS BOOLEAN) AS COMPUTE_FOR_SHORT_TERM,
    CAST(CONTRACTENABLED AS BOOLEAN) AS CONTRACT_ENABLED,
    CAST(DROPSHIP AS BOOLEAN) AS DROP_SHIP,
    CAST(ENABLE_REPLENISHMENT AS BOOLEAN) AS ENABLE_REPLENISHMENT,
    CAST(ENABLEFULFILLMENT AS BOOLEAN) AS ENABLE_FULFILLMENT,
    CAST(ENABLELANDEDCOST AS BOOLEAN) AS ENABLE_LANDED_COST,
    CAST(ENGINEERINGAPPROVAL AS BOOLEAN) AS ENGINEERING_APPROVAL,
    CAST(GIFTCARD AS BOOLEAN) AS GIFT_CARD,
    CAST(HASSTARTENDDATES AS BOOLEAN) AS HAS_START_END_DATES,
    CAST(ISSUPPLYITEM AS BOOLEAN) AS IS_SUPPLY_ITEM,
    CAST(MRR AS BOOLEAN) AS MRR,
    CAST(QUALITYCONTROLAPPROVAL AS BOOLEAN) AS QUALITY_CONTROL_APPROVAL,
    CAST(RESTRICTEDITEM AS BOOLEAN) AS RESTRICTED_ITEM,
    CAST(SAFETYITEM AS BOOLEAN) AS SAFETY_ITEM,
    CAST(SALESAPPROVAL AS BOOLEAN) AS SALES_APPROVAL,
    CAST(TAXABLE AS BOOLEAN) AS TAXABLE,
    CAST(WEBENABLED AS BOOLEAN) AS WEB_ENABLED,

    -- Financials / Pricing
    BASEPRICE AS BASE_PRICE,                    -- numeric, no cast
    TRIM(BASEUOM) AS BASE_UOM,
    TRIM(COST_METHOD) AS COST_METHOD,
    TRIM(GLGROUP) AS GL_GROUP,
    TRY_CAST(GLGRPKEY AS INT) AS GL_GROUP_KEY,
    STANDARD_COST AS STANDARD_COST,             -- float
    IONHAND AS INVENTORY_ON_HAND,               -- float
    TRY_CAST(IONORDER AS INT) AS INVENTORY_ON_ORDER,
    IUNCOMMITTED AS INVENTORY_UNCOMMITTED,      -- float
    TRY_CAST(MAX_ORDER_QTY AS INT) AS MAX_ORDER_QTY,
    TRY_CAST(REORDER_POINT AS INT) AS REORDER_POINT,
    TRY_CAST(REORDER_QTY AS INT) AS REORDER_QTY,
    TRY_CAST(SAFETY_STOCK AS INT) AS SAFETY_STOCK,
    TRIM(REPLENISHMENT_METHOD) AS REPLENISHMENT_METHOD,
    TRIM(DEFAULT_CONVERSIONTYPE) AS DEFAULT_CONVERSION_TYPE,
    TRIM(DEFAULT_REPLENISHMENT_UOM) AS DEFAULT_REPLENISHMENT_UOM,

    -- Rev Rec & Contract
    TRY_CAST(DEFAULTREVRECTEMPLKEY AS INT) AS DEFAULT_REV_REC_TEMPLATE_KEY,
    TRIM(DEFCONTRACTDEFERRALSTATUS) AS DEF_CONTRACT_DEFERRAL_STATUS,
    TRIM(DEFCONTRACTDELIVERYSTATUS) AS DEF_CONTRACT_DELIVERY_STATUS,
    TRY_CAST(DEFERREDREVACCTKEY AS INT) AS DEFERRED_REV_ACCT_KEY,
    TRIM(REVPRINTING) AS REV_PRINTING,
    TRIM(VSOECATEGORY) AS VSOE_CATEGORY,
    TRIM(VSOEDLVRSTATUS) AS VSOE_DELIVERY_STATUS,
    TRIM(VSOEREVDEFSTATUS) AS VSOE_REV_DEF_STATUS,

    -- Units of Measure
    TRIM(UOM_INVUOMDETAIL_UNIT) AS UOM_INV_UNIT,
    TRY_CAST(UOM_POUOMDETAIL_CONVFACTOR AS INT) AS UOM_PO_CONV_FACTOR,
    TRIM(UOM_POUOMDETAIL_UNIT) AS UOM_PO_UNIT,
    TRY_CAST(UOM_SOUOMDETAIL_CONVFACTOR AS INT) AS UOM_SO_CONV_FACTOR,
    TRIM(UOM_SOUOMDETAIL_UNIT) AS UOM_SO_UNIT,
    TRIM(UOMGRP) AS UOM_GROUP,
    TRY_CAST(UOMGRPKEY AS INT) AS UOM_GROUP_KEY,

    -- Extra
    TRIM(EXTENDED_DESCRIPTION) AS EXTENDED_DESCRIPTION,
    TRIM(NOTE) AS NOTE,

    -- Relationships
    TRY_CAST(CREATEDBY AS INT) AS CREATED_BY,
    TRY_CAST(MODIFIEDBY AS INT) AS MODIFIED_BY,

    -- Dates
    CAST(WHENCREATED AS TIMESTAMP_NTZ) AS WHEN_CREATED,
    CAST(WHENMODIFIED AS TIMESTAMP_NTZ) AS WHEN_MODIFIED,
    CAST(WHENLASTSOLD AS DATE) AS WHEN_LAST_SOLD,
    CAST(WHENLASTRECEIVED AS DATE) AS WHEN_LAST_RECEIVED,

    -- Audit
    _FIVETRAN_DELETED AS IS_DELETED,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE

FROM {{ source('spotless_sage', 'ITEM') }}

{% if is_incremental() %}
WHERE WHENMODIFIED > (
    SELECT COALESCE(MAX(WHEN_MODIFIED), '1900-01-01'::TIMESTAMP_NTZ)
    FROM {{ this }}
)
{% endif %}
