{{ config(
    materialized = 'incremental',
    unique_key = 'RECORD_NO',
    incremental_strategy = 'merge'
) }}

SELECT
    -- Primary Key
    TRY_CAST(RECORDNO AS INT) AS RECORD_NO,

    -- Core Identifiers
    TRIM(LOCATIONID) AS LOCATION_ID,
    TRIM(NAME) AS LOCATION_NAME,
    TRIM(ENTITY) AS ENTITY,
    TRIM(SPLIT_PART(ENTITY,'--',1)) AS ENTITY_CODE,
    TRIM(SPLIT_PART(ENTITY,'--',2)) AS ENTITY_DESCRIPTION,
    TRIM(STATUS) AS STATUS,

    -- Accounting & Legal
    TRIM(ACCOUNTINGTYPE) AS ACCOUNTING_TYPE,
    TRIM(LEGALCOUNTRYCODE) AS LEGAL_COUNTRY_CODE,
    TRIM(FEDERALID) AS FEDERAL_ID,
    TRIM(CUSTTITLE) AS CUSTOMER_TITLE,
    TRIM(OPCOUNTRY) AS OP_COUNTRY,
    TRIM(REPORTPRINTAS) AS REPORT_PRINT_AS,
    TRIM(TAXID) AS TAX_ID,

    -- Dates
    CAST(STARTOPEN AS DATE) AS START_OPEN,
    CAST(STATUTORYREPORTINGPERIOD AS DATE) AS STATUTORY_REPORTING_PERIOD,
    CAST(WHENCREATED AS TIMESTAMP_NTZ) AS WHEN_CREATED,
    CAST(WHENMODIFIED AS TIMESTAMP_NTZ) AS WHEN_MODIFIED,

    -- Flags
    CAST(DEFAULTPARTIALEXEMPT AS BOOLEAN) AS DEFAULT_PARTIAL_EXEMPT,
    CAST(ENABLELEGALCONTACT AS BOOLEAN) AS ENABLE_LEGAL_CONTACT,
    CAST(ENABLELEGALCONTACT_TPAR AS BOOLEAN) AS ENABLE_LEGAL_CONTACT_TPAR,
    CAST(HAS_IE_RELATION AS BOOLEAN) AS HAS_IE_RELATION,
    CAST(ISLIMITEDENTITY AS BOOLEAN) AS IS_LIMITED_ENTITY,
    CAST(ISROOT AS BOOLEAN) AS IS_ROOT,
    CAST(PARTIALEXEMPT AS BOOLEAN) AS PARTIAL_EXEMPT,

    -- Misc
    TRIM(ADDRESSCOUNTRYDEFAULT) AS ADDRESS_COUNTRY_DEFAULT,
    TRIM(BUSINESSDAYS) AS BUSINESS_DAYS,
    TRIM(WEEKENDS) AS WEEKENDS,
    TRY_CAST(FIRSTMONTH AS INT) AS FIRST_MONTH,
    TRY_CAST(FIRSTMONTHTAX AS INT) AS FIRST_MONTH_TAX,

    -- Relationships
    TRY_CAST(CREATEDBY AS INT) AS CREATED_BY,
    TRY_CAST(MODIFIEDBY AS INT) AS MODIFIED_BY,

    -- Audit
    _FIVETRAN_DELETED AS IS_DELETED,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE

FROM {{ source('spotless_sage', 'LOCATION_ENTITY') }}

{% if is_incremental() %}
WHERE WHENMODIFIED > (
    SELECT COALESCE(MAX(WHEN_MODIFIED), '1900-01-01'::TIMESTAMP_NTZ)
    FROM {{ this }}
)
{% endif %}
