{{ config(
    materialized = 'incremental',
    unique_key = 'RECORD_NO',
    incremental_strategy = 'merge'
) }}

SELECT
    -- Primary Key
    TRY_CAST(RECORDNO AS INT) AS RECORD_NO,

    -- Foreign Keys & Identifiers
    TRY_CAST(ACCOUNTKEY AS INT) AS ACCOUNT_KEY,
    TRIM(ACCOUNTNO) AS ACCOUNT_NO,
    TRIM(ACCOUNTTITLE) AS ACCOUNT_TITLE,
    TRY_CAST(BATCH_NUMBER AS INT) AS BATCH_NUMBER,
    TRIM(BATCHNO) AS BATCH_NO,
    TRIM(BATCHTITLE) AS BATCH_TITLE,
    TRY_CAST(CLASSDIMKEY AS INT) AS CLASS_DIM_KEY,
    TRIM(CLASSID) AS CLASS_ID,
    TRIM(CLASSNAME) AS CLASS_NAME,
    TRY_CAST(DEPARTMENTKEY AS INT) AS DEPARTMENT_KEY,
    TRIM(DEPARTMENT) AS DEPARTMENT,
    TRIM(DEPARTMENTTITLE) AS DEPARTMENT_TITLE,
    TRY_CAST(ITEMDIMKEY AS INT) AS ITEM_DIM_KEY,
    TRIM(ITEMID) AS ITEM_ID,
    TRIM(ITEMNAME) AS ITEM_NAME,
    TRY_CAST(PROJECTDIMKEY AS INT) AS PROJECT_DIM_KEY,
    TRIM(PROJECTID) AS PROJECT_ID,
    TRIM(PROJECTNAME) AS PROJECT_NAME,
    TRIM(LOCATION) AS LOCATION,
    TRY_CAST(LOCATIONKEY AS INT) AS LOCATION_KEY,
    TRIM(LOCATIONNAME) AS LOCATION_NAME,
    TRY_CAST(VENDORDIMKEY AS INT) AS VENDOR_DIM_KEY,
    TRY_CAST(VENDORID AS INT) AS VENDOR_ID,
    TRIM(VENDORNAME) AS VENDOR_NAME,
    TRY_CAST(WAREHOUSEDIMKEY AS INT) AS WAREHOUSE_DIM_KEY,
    TRIM(WAREHOUSEID) AS WAREHOUSE_ID,
    TRIM(WAREHOUSENAME) AS WAREHOUSE_NAME,

    -- Core Attributes
    TRIM(DESCRIPTION) AS DESCRIPTION,
    TRIM(DOCUMENT) AS DOCUMENT,
    TRIM(STATE) AS STATE,
    ADJ AS IS_ADJ,
    BILLABLE AS IS_BILLABLE,
    STATISTICAL AS IS_STATISTICAL,
    TRY_CAST(LINE_NO AS INT) AS LINE_NO,
    TRY_CAST(TR_TYPE AS INT) AS TR_TYPE,

    -- Amounts, Currency & Exchange
    AMOUNT,
    TRX_AMOUNT, 
    TRIM(CURRENCY) AS CURRENCY,
    TRIM(BASECURR) AS BASE_CURRENCY,
    TRY_CAST(EXCHANGE_RATE AS INT) AS EXCHANGE_RATE,
    TRY_CAST(EXCH_RATE_TYPE_ID AS INT) AS EXCH_RATE_TYPE_ID,
    CAST(EXCH_RATE_DATE AS DATE) AS EXCH_RATE_DATE,
    TRY_CAST(GLDIMREVENUE_CENTER AS INT) AS GL_DIM_REVENUE_CENTER,

    -- Dates
    CAST(BATCH_DATE AS DATE) AS BATCH_DATE,
    CAST(ENTRY_DATE AS DATE) AS ENTRY_DATE,
    CAST(CLRDATE AS DATE) AS CLR_DATE,
    CAST(WHENCREATED AS TIMESTAMP_NTZ) AS WHEN_CREATED,
    CAST(WHENMODIFIED AS TIMESTAMP_NTZ) AS WHEN_MODIFIED,

    -- Audit
    TRY_CAST(CREATEDBY AS INT) AS CREATED_BY,
    TRIM(CREATEDBYLOGINID) AS CREATED_BY_LOGIN_ID,
    TRY_CAST(MODIFIEDBY AS INT) AS MODIFIED_BY,
    TRIM(MODIFIEDBYLOGINID) AS MODIFIED_BY_LOGIN_ID,
    TRY_CAST(USERNO AS INT) AS USER_NO,

    -- Metadata
    TRIM(RECORD_URL) AS RECORD_URL,
    TRY_CAST(RDEPRECIATION_SUMMARY AS INT) AS R_DEPRECIATION_SUMMARY,

    -- Silver Load Metadata
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE

FROM {{ source('spotless_sage', 'GL_ENTRY') }}

{% if is_incremental() %}
WHERE WHENCREATED > (
    SELECT COALESCE(MAX(WHEN_MODIFIED), '1900-01-01'::TIMESTAMP_NTZ)
    FROM {{ this }}
)
{% endif %}
