{{ config(
    materialized = 'incremental',
    unique_key = 'BATCH_NO',
    incremental_strategy = 'merge'
) }}

SELECT
    -- Primary Key
    TRY_CAST(BATCHNO AS INT) AS BATCH_NO,

    -- Core Identifiers
    TRY_CAST(RECORDNO AS INT) AS RECORD_NO,
    TRIM(BATCH_TITLE) AS BATCH_TITLE,
    TRY_CAST(BASELOCATION AS INT) AS BASE_LOCATION,
    TRIM(BASELOCATION_NO) AS BASE_LOCATION_NO,
    TRIM(JOURNAL) AS JOURNAL,
    TRIM(MODULE) AS MODULE,
    TRIM(STATE) AS STATE,
    TRIM(TAXIMPLICATIONS) AS TAX_IMPLICATIONS,
    TRIM(TRANSACTIONSOURCE) AS TRANSACTION_SOURCE,

    -- Entity Info
    TRIM(MEGAENTITYID) AS MEGA_ENTITY_ID,
    TRY_CAST(MEGAENTITYKEY AS INT) AS MEGA_ENTITY_KEY,
    TRIM(MEGAENTITYNAME) AS MEGA_ENTITY_NAME,

    -- References
    TRIM(REFERENCENO) AS REFERENCE_NO,
    TRIM(RECORD_URL) AS RECORD_URL,
    TRY_CAST(PRBATCHKEY AS INT) AS PR_BATCH_KEY,
    TRY_CAST(REVERSEDKEY AS INT) AS REVERSED_KEY,
    TRY_CAST(RFIXED_ASSETS_LOG AS INT) AS R_FIXED_ASSETS_LOG,
    TRY_CAST(RDEPRECIATION_SCHEDULE AS INT) AS R_DEPRECIATION_SCHEDULE,
    TRY_CAST(RPESENTRY AS INT) AS R_PES_ENTRY,
    TRY_CAST(SCHOPKEY AS INT) AS SCHOP_KEY,
    TRY_CAST(SUPDOCKEY AS INT) AS SUPDOC_KEY,
    TRIM(SUPDOCID) AS SUPDOC_ID,
    TRY_CAST(USERKEY AS INT) AS USER_KEY,
    TRIM(USERINFO_LOGINID) AS USERINFO_LOGIN_ID,

    -- Flags
    STATISTICAL AS IS_STATISTICAL,

    -- Dates
    CAST(BATCH_DATE AS DATE) AS BATCH_DATE,
    CAST(REVERSED AS DATE) AS REVERSED_DATE,
    CAST(REVERSEDFROM AS DATE) AS REVERSED_FROM_DATE,

    -- Audit
    TRY_CAST(CREATEDBY AS INT) AS CREATED_BY,
    TRIM(CREATEDBYLOGINID) AS CREATED_BY_LOGIN_ID,
    TRY_CAST(MODIFIEDBY AS INT) AS MODIFIED_BY,
    TRIM(MODIFIEDBYID) AS MODIFIED_BY_ID,
    TRIM(MODIFIEDBYLOGINID) AS MODIFIED_BY_LOGIN_ID,
    CAST(WHENCREATED AS TIMESTAMP_NTZ) AS CREATED_DATE,
    CAST(WHENMODIFIED AS TIMESTAMP_NTZ) AS WHEN_MODIFIED,
    CAST(MODIFIED AS TIMESTAMP_NTZ) AS MODIFIED_DATE,
    _FIVETRAN_DELETED AS IS_DELETED,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE

FROM {{ source('spotless_sage', 'GL_BATCH') }}

{% if is_incremental() %}
WHERE WHENMODIFIED > (
    SELECT COALESCE(MAX(WHEN_MODIFIED), '1900-01-01'::TIMESTAMP_NTZ)
    FROM {{ this }}
)
{% endif %}
