{{ config(
    materialized = 'incremental',
    unique_key = 'DEPRECIATION_SUMMARY_ID',
    incremental_strategy = 'merge'
) }}

SELECT
    TRY_CAST(ID AS INT) AS DEPRECIATION_SUMMARY_ID,
    TRY_CAST(AMOUNT AS FLOAT) AS AMOUNT,
    TRY_CAST(NAME AS INT) AS NAME,

    COALESCE(
        TRY_TO_DATE(GL_POSTING_DATE, 'MM/DD/YYYY'),
        TRY_TO_DATE(GL_POSTING_DATE, 'YYYY-MM-DD'),
        TRY_TO_DATE(GL_POSTING_DATE, 'MM-DD-YY')
    ) AS GL_POSTING_DATE,

    TRY_CAST(CREATED_AT AS TIMESTAMP_NTZ) AS CREATED_AT,
    TRY_CAST(UPDATED_AT AS TIMESTAMP_NTZ) AS UPDATED_AT,

    -- Split RDEPARTMENT
    TRY_CAST(REGEXP_SUBSTR(DIMENSIONS, 'RDEPARTMENT: ([0-9]+)--', 1, 1, 'e', 1) AS INT) AS RDEPARTMENT_ID,
    TRIM(REGEXP_SUBSTR(DIMENSIONS, 'RDEPARTMENT: [0-9]+--([^,]+)', 1, 1, 'e', 1)) AS RDEPARTMENT_NAME,

    -- Split RLOCATION
    TRY_CAST(REGEXP_SUBSTR(DIMENSIONS, 'RLOCATION: ([0-9]+)--', 1, 1, 'e', 1) AS INT) AS RLOCATION_ID,
    TRIM(REGEXP_SUBSTR(DIMENSIONS, 'RLOCATION: [0-9]+--([^,]+)', 1, 1, 'e', 1)) AS RLOCATION_NAME,

    -- Split RREVENUE_CENTER
    TRY_CAST(REGEXP_SUBSTR(DIMENSIONS, 'Rrevenue_center: ([0-9]+)--', 1, 1, 'e', 1) AS INT) AS RREVENUE_CENTER_ID,
    TRIM(REGEXP_SUBSTR(DIMENSIONS, 'Rrevenue_center: [0-9]+--([^,]+)', 1, 1, 'e', 1)) AS RREVENUE_CENTER_NAME,

    -- Split RVENDOR
    TRY_CAST(REGEXP_SUBSTR(DIMENSIONS, 'RVENDOR: ([0-9]+)--', 1, 1, 'e', 1) AS INT) AS RVENDOR_ID,
    TRIM(REGEXP_SUBSTR(DIMENSIONS, 'RVENDOR: [0-9]+--([^,]+)', 1, 1, 'e', 1)) AS RVENDOR_NAME,

    -- Split RCLASS
    TRY_CAST(REGEXP_SUBSTR(DIMENSIONS, 'RCLASS: ([0-9]+)--', 1, 1, 'e', 1) AS INT) AS RCLASS_ID,
    TRIM(REGEXP_SUBSTR(DIMENSIONS, 'RCLASS: [0-9]+--([^,]+)', 1, 1, 'e', 1)) AS RCLASS_NAME,

    _FIVETRAN_DELETED AS IS_DELETED,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE

FROM {{ source('spotless_sage', 'DEPRECIATION_SUMMARY') }}
{% if is_incremental() %}
WHERE UPDATED_AT > (
    SELECT COALESCE(MAX(UPDATED_AT), '1900-01-01'::TIMESTAMP_NTZ)
    FROM {{ this }}
)
{% endif %}
