{{ config(
    materialized = 'incremental',
    unique_key = 'REPORTING_PERIOD_ID',
    incremental_strategy = 'merge'
) }}

SELECT
    -- Primary Key
    TRY_CAST(RECORDNO AS INT) AS REPORTING_PERIOD_ID,

    -- Core Info
    TRIM(NAME) AS REPORTING_PERIOD_NAME,
    TRIM(STATUS) AS STATUS,
    TRY_CAST(DATETYPE AS FLOAT) AS DATE_TYPE,
    CAST(BUDGETING AS BOOLEAN) AS IS_BUDGETING,

    -- Headers
    TRIM(HEADER_1) AS HEADER_1,
    TRIM(HEADER_2) AS HEADER_2,

    -- Dates
    CAST(START_DATE AS DATE) AS START_DATE,
    CAST(END_DATE AS DATE) AS END_DATE,
    CAST(WHENCREATED AS TIMESTAMP_NTZ) AS WHEN_CREATED,
    CAST(WHENMODIFIED AS TIMESTAMP_NTZ) AS WHEN_MODIFIED,

    -- Fivetran
    _FIVETRAN_DELETED AS IS_DELETED,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE

FROM {{ source('spotless_sage', 'REPORTING_PERIOD') }}

{% if is_incremental() %}
WHERE WHENMODIFIED > (
    SELECT COALESCE(MAX(WHEN_MODIFIED), '1900-01-01'::TIMESTAMP_NTZ)
    FROM {{ this }}
)
{% endif %}
