{{ config(
    materialized = 'incremental',
    incremental_strategy = 'merge',
    unique_key = ['EMPLOYEE_ID','SOURCESYSTEM','COMPANY']
) }}

select
    CAST(NULL AS VARCHAR) AS ACCOUNT_NUMBER
    ,CLASS_ID
    ,DATE_CREATED
    ,CURRENCY
    ,DEPATMENT_ID
    ,EMAIL
    ,TO_VARCHAR(EMPLOYEE_ID) AS EMPLOYEE_ID
    ,EMPLOYEE_TYPE_ID
    ,ENTITY_ID
    ,TO_VARCHAR(IS_INACTIVE) AS IS_INACTIVE
    ,JOB_DESCRIPTION
    ,LAST_MODIFIED_DATE
    ,LOCATION_ID
    ,EMPLOYEE_STATUS_ID
    ,SUBSIDIARY
    ,TITLE
    ,'NETSUITE' AS SOURCESYSTEM,
    'WAGWAY' AS COMPANY,
     CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS CONSOLIDATED_GOLD_LOAD_DATE
from {{ env_var('DBT_WAGWAY', 'wagway_dev') }}.gold.NETSUITE_DIM_EMPLOYEE


union all

select
    CAST(NULL AS VARCHAR) AS ACCOUNT_NUMBER
    ,CLASS_ID
    ,DATE_CREATED
    ,CURRENCY
    ,DEPATMENT_ID
    ,EMAIL
    ,TO_VARCHAR(EMPLOYEE_ID) AS EMPLOYEE_ID
    ,EMPLOYEE_TYPE_ID
    ,ENTITY_ID
    ,TO_VARCHAR(IS_INACTIVE) AS IS_INACTIVE
    ,JOB_DESCRIPTION
    ,LAST_MODIFIED_DATE
    ,LOCATION_ID
    ,EMPLOYEE_STATUS_ID
    ,SUBSIDIARY
    ,TITLE
    ,'NETSUITE' AS SOURCESYSTEM,
    'PLAYFLY' AS COMPANY,
     CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS CONSOLIDATED_GOLD_LOAD_DATE
from {{ env_var('DBT_PLAYFLY', 'playfly_dev') }}.gold.NETSUITE_DIM_EMPLOYEE

union all

select

    CAST(NULL AS VARCHAR) AS ACCOUNT_NUMBER
    ,NULL AS CLASS_ID
    ,DATE_CREATED
    ,NULL AS CURRENCY
    ,DEPARTMENT_ID
    ,EMAIL
    ,EMPLOYEE_ID
    ,EMPLOYEE_TYPE_ID
    ,ENTITY_ID
    ,TO_VARCHAR(IS_INACTIVE) AS IS_INACTIVE
    ,NULL AS JOB_DESCRIPTION
    ,LAST_MODIFIED_DATE
    ,LOCATION_ID
    ,NULL AS EMPLOYEE_STATUS_ID
    ,SUBSIDIARY_ID
    ,TITLE AS TITLE
    ,'SAGE' AS SOURCESYSTEM,
    'SPOTLESS' AS COMPANY,
     CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS CONSOLIDATED_GOLD_LOAD_DATE
from {{ env_var('DBT_SPOTLESS', 'spotless_dev') }}.gold.SAGE_DIM_EMPLOYEE

