{{ config(
    materialized = 'incremental',
    incremental_strategy = 'merge',
    unique_key = ['SUBSIDIARY_ID','SOURCESYSTEM','COMPANY']
) }}

select
    TO_VARCHAR(SUBSIDIARY_ID) AS SUBSIDIARY_ID,
    SUBSIDIARY_NAME,
    SUBSIDIARY_FULL_NAME,
    PARENT_ID,
    CURRENCY_ID,
    TO_VARCHAR(IS_INACTIVE) AS IS_INACTIVE,
    LAST_MODIFIED_DATE,
    'NETSUITE' AS SOURCESYSTEM,
    'WAGWAY' AS COMPANY,
     CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS CONSOLIDATED_GOLD_LOAD_DATE
from {{ env_var('DBT_WAGWAY', 'wagway_dev') }}.gold.NETSUITE_DIM_SUBSIDIARY


union all

select
    TO_VARCHAR(SUBSIDIARY_ID) AS SUBSIDIARY_ID,
    SUBSIDIARY_NAME,
    SUBSIDIARY_FULL_NAME,
    PARENT_ID,
    CURRENCY_ID,
    TO_VARCHAR(IS_INACTIVE) AS IS_INACTIVE,
    LAST_MODIFIED_DATE,
    'NETSUITE' AS SOURCESYSTEM,
    'PLAYFLY' AS COMPANY,
     CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS CONSOLIDATED_GOLD_LOAD_DATE
from {{ env_var('DBT_PLAYFLY', 'playfly_dev') }}.gold.NETSUITE_DIM_SUBSIDIARY

union all

select
    SUBSIDIARY_ID,
    SUBSIDIARY_TITLE AS SUBSIDIARY_NAME,
    'N/A' AS SUBSIDIARY_FULL_NAME,
    CAST(NULL AS VARCHAR) AS PARENT_ID,
    CAST(NULL AS VARCHAR) AS CURRENCY_ID,
    IS_INACTIVE,
    LAST_MODIFIED_DATE,
    'SAGE' AS SOURCESYSTEM,
    'SPOTLESS' AS COMPANY,
     CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS CONSOLIDATED_GOLD_LOAD_DATE
from {{ env_var('DBT_SPOTLESS', 'spotless_dev') }}.gold.SAGE_DIM_SUBSIDIARY

union all

select
    SUBSIDIARY_ID,
    SUBSIDIARY_TITLE AS SUBSIDIARY_NAME,
    'N/A' AS SUBSIDIARY_FULL_NAME,
    CAST(NULL AS VARCHAR) AS PARENT_ID,
    CAST(NULL AS VARCHAR) AS CURRENCY_ID,
    IS_INACTIVE,
    LAST_MODIFIED_DATE,
    'SAGE' AS SOURCESYSTEM,
    'SPOTLESS' AS COMPANY,
     CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS CONSOLIDATED_GOLD_LOAD_DATE
from {{ env_var('DBT_AMH', 'amh_dev') }}.gold.SAGE_DIM_SUBSIDIARY