{{ config(
    materialized = 'incremental',
    incremental_strategy = 'merge',
    unique_key = ['CURRENCY_ID','SOURCESYSTEM','COMPANY']
) }}

select
    CURRENCY_ID,
    CURRENCY_NAME,
    DISPLAY_SYMBOL,
    IS_INACTIVE,
    IS_BASE_CURRENCY,
    LAST_MODIFIED_DATE,
    'NETSUITE' AS SOURCESYSTEM,
    'WAGWAY' AS COMPANY,
     CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS CONSOLIDATED_GOLD_LOAD_DATE
from {{ env_var('DBT_WAGWAY', 'wagway_dev') }}.gold.NETSUITE_DIM_CURRENCY

union all

select
    CURRENCY_ID,
    CURRENCY_NAME,
    DISPLAY_SYMBOL,
    IS_INACTIVE,
    IS_BASE_CURRENCY,
    LAST_MODIFIED_DATE,
    'NETSUITE' AS SOURCESYSTEM,
    'PLAYFLY' AS COMPANY,
     CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS CONSOLIDATED_GOLD_LOAD_DATE
from {{ env_var('DBT_PLAYFLY', 'playfly_dev') }}.gold.NETSUITE_DIM_CURRENCY


union all

select
    DIM_CURRENCY_ID AS CURRENCY_ID,
    CURRENCY_NAME,
    DISPLAY_SYMBOL,
    NULL AS IS_INACTIVE,
    NULL AS IS_BASE_CURRENCY,
    LAST_MODIFIED_DATE,
    'SAGE' AS SOURCESYSTEM,
    'SPOTLESS' AS COMPANY,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS CONSOLIDATED_GOLD_LOAD_DATE
from {{ env_var('DBT_SPOTLESS', 'spotless_dev') }}.gold.SAGE_DIM_CURRENCY