{{ config(
    materialized = 'incremental',
    incremental_strategy = 'merge',
    unique_key = ['LOCATION_ID','SOURCESYSTEM','COMPANY']
) }}

select
    LOCATION_ID,
    LOCATION_NAME,
    PARENT,
    SUBSIDIARY_ID,
    IS_INACTIVE,
    LAST_MODIFIED_DATE,
    'NETSUITE' AS SOURCESYSTEM,
    'WAGWAY' AS COMPANY,
     CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS CONSOLIDATED_GOLD_LOAD_DATE
from {{ env_var('DBT_WAGWAY', 'wagway_dev') }}.gold.NETSUITE_DIM_LOCATION


union all

select
    LOCATION_ID,
    LOCATION_NAME,
    PARENT,
    SUBSIDIARY_ID,
    IS_INACTIVE,
    LAST_MODIFIED_DATE,
    'NETSUITE' AS SOURCESYSTEM,
    'PLAYFLY' AS COMPANY,
     CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS CONSOLIDATED_GOLD_LOAD_DATE
from {{ env_var('DBT_PLAYFLY', 'playfly_dev') }}.gold.NETSUITE_DIM_LOCATION

union all

select
    LOCATION_ID,
    LOCATION_NAME,
    PARENT,
    SUBSIDIARY_ID,
    IS_INACTIVE,
    LAST_MODIFIED_DATE,
    'SAGE' AS SOURCESYSTEM,
    'SPOTLESS' AS COMPANY,
     CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS CONSOLIDATED_GOLD_LOAD_DATE
from {{ env_var('DBT_SPOTLESS', 'spotless_dev') }}.gold.SAGE_DIM_LOCATION

union all

select
    LOCATION_ID,
    LOCATION_NAME,
    PARENT,
    SUBSIDIARY_ID,
    IS_INACTIVE,
    LAST_MODIFIED_DATE,
    'SAGE' AS SOURCESYSTEM,
    'AMH' AS COMPANY,
     CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS CONSOLIDATED_GOLD_LOAD_DATE
from {{ env_var('DBT_AMH', 'amh_dev') }}.gold.SAGE_DIM_LOCATION

