{{ config(
    materialized = 'incremental',
    incremental_strategy = 'merge',
    unique_key = ['DIM_ACCOUNT_ID','COMPANY']
) }}

select
    DIM_ACCOUNT_ID,
    ACCOUNT_ID,
    ACCOUNT_NAME,
    MAIN_ACCOUNT_NAME,
    ACCOUNT_NAME_SUBCATEGORY_1,
    ACCOUNT_NAME_SUBCATEGORY_2,
    ACCOUNT_NAME_SUBCATEGORY_3,
    ACCOUNT_NUMBER,
    ACCOUNT_DESCRIPTION,
    ACCOUNT_PARENT_ID,
    CAST(ACCOUNT_SUBSIDIARY_ID AS TEXT) AS ACCOUNT_SUBSIDIARY_ID,
    LOCATION_ID,
    ACCOUNT_TYPE,
    DEPARTMENT_ID,
    DISPLAY_NAME,
    DISPLAY_NAME_WITH_HIERARCHY,
    CURRENCY_ID,
    SUBSIDIARY_PARENT_ID,
    SUBSIDIARY_FULL_NAME,
    SUBSIDIARY_NAME,
    'NETSUITE' AS SOURCESYSTEM,
    'WAGWAY' AS COMPANY,
     CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS CONSOLIDATED_GOLD_LOAD_DATE
from {{ env_var('DBT_WAGWAY', 'wagway_dev') }}.gold.NETSUITE_DIM_CHART_OF_ACCOUNT

union all

select
    DIM_ACCOUNT_ID,
    ACCOUNT_ID,
    ACCOUNT_NAME,
    MAIN_ACCOUNT_NAME,
    ACCOUNT_NAME_SUBCATEGORY_1,
    ACCOUNT_NAME_SUBCATEGORY_2,
    ACCOUNT_NAME_SUBCATEGORY_3,
    ACCOUNT_NUMBER,
    ACCOUNT_DESCRIPTION,
    ACCOUNT_PARENT_ID,
    CAST(ACCOUNT_SUBSIDIARY_ID AS TEXT) AS ACCOUNT_SUBSIDIARY_ID,
    LOCATION_ID,
    ACCOUNT_TYPE,
    DEPARTMENT_ID,
    DISPLAY_NAME,
    DISPLAY_NAME_WITH_HIERARCHY,
    CURRENCY_ID,
    SUBSIDIARY_PARENT_ID,
    SUBSIDIARY_FULL_NAME,
    SUBSIDIARY_NAME,
    'NETSUITE' AS SOURCESYSTEM,
    'PLAYFLY' AS COMPANY,
     CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS CONSOLIDATED_GOLD_LOAD_DATE
from {{ env_var('DBT_PLAYFLY', 'playfly_dev') }}.gold.NETSUITE_DIM_CHART_OF_ACCOUNT

union all

select
    DIM_ACCOUNT_ID,
    ACCOUNT_ID,
    ACCOUNT_TITLE AS ACCOUNT_NAME,
    CAST(NULL AS TEXT) AS MAIN_ACCOUNT_NAME,
    CAST(NULL AS TEXT) AS ACCOUNT_NAME_SUBCATEGORY_1,
    CAST(NULL AS TEXT) AS ACCOUNT_NAME_SUBCATEGORY_2,
    CAST(NULL AS TEXT) AS ACCOUNT_NAME_SUBCATEGORY_3,
    CAST(ACCOUNT_NO AS TEXT) AS ACCOUNT_NUMBER,
    CAST(NULL AS TEXT) AS ACCOUNT_DESCRIPTION,
    CAST(NULL AS NUMBER) AS ACCOUNT_PARENT_ID,
    SUBSIDIARY_ID AS ACCOUNT_SUBSIDIARY_ID,
    CAST(NULL AS NUMBER) AS LOCATION_ID,
    ACCOUNTTYPE AS ACCOUNT_TYPE,
    CAST(NULL AS NUMBER) AS DEPARTMENT_ID,
    CAST(NULL AS TEXT) AS DISPLAY_NAME,
    CAST(NULL AS TEXT) AS DISPLAY_NAME_WITH_HIERARCHY,
    CAST(NULL AS NUMBER) AS CURRENCY_ID,
    CAST(NULL AS NUMBER) AS SUBSIDIARY_PARENT_ID,
    NULL AS SUBSIDIARY_FULL_NAME,
    SUBSIDIARY_NAME,
    'SAGE' AS SOURCESYSTEM,
    'SPOTLESS' AS COMPANY,
     CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS CONSOLIDATED_GOLD_LOAD_DATE
from {{ env_var('DBT_SPOTLESS', 'spotless_dev') }}.gold.SAGE_DIM_CHART_OF_ACCOUNT