{{ config(
    materialized = 'incremental',
    incremental_strategy = 'merge',
    unique_key = ['ITEM_ID','SOURCESYSTEM','COMPANY']
) }}

select
    ITEM_ID
    ,ITEM_FULL_NAME
    ,ITEM_NAME
    ,DISPLAY_NAME
    ,DESCRIPTION
    ,STORE_DISPLAY_NAME
    ,STORE_DESCRIPTION
    ,STORE_DETAILED_DESCRIPTION
    ,ITEM_TYPE
    ,SUB_TYPE
    ,CLASS_ID
    ,DEPARTMENT_ID
    ,LOCATION_ID
    ,SUBSIDIARY
    ,PARENT
    ,PRICING_GROUP
    ,UNITS_TYPE
    ,INCOME_ACCOUNT
    ,COSTING_METHOD
    ,COST
    ,LAST_PURCHASE_PRICE
    ,AVERAGE_COST
    ,TOTAL_QUANTITY_ON_HAND
    ,TOTAL_VALUE
    ,SALEUNIT
    ,STOCK_UNIT
    ,SHIPPING_COST
    ,VENDOR_NAME
    ,MANUFACTURER
    ,MAXIMUN_QUANTITY
    ,WEIGHT
    ,IS_FUL_FILLABLE
    ,CAST(IS_INACTIVE AS VARCHAR) AS IS_INACTIVE
    ,CREATED_DATE
    ,LAST_MODIFIED_DATE
    ,'NETSUITE' AS SOURCESYSTEM,
    'WAGWAY' AS COMPANY,
     CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS CONSOLIDATED_GOLD_LOAD_DATE
from {{ env_var('DBT_WAGWAY', 'wagway_dev') }}.gold.NETSUITE_DIM_ITEM

union all

select
    ITEM_ID
    ,ITEM_FULL_NAME
    ,ITEM_NAME
    ,DISPLAY_NAME
    ,DESCRIPTION
    ,STORE_DISPLAY_NAME
    ,STORE_DESCRIPTION
    ,STORE_DETAILED_DESCRIPTION
    ,ITEM_TYPE
    ,SUB_TYPE
    ,CLASS_ID
    ,DEPARTMENT_ID
    ,LOCATION_ID
    ,SUBSIDIARY
    ,PARENT
    ,PRICING_GROUP
    ,UNITS_TYPE
    ,INCOME_ACCOUNT
    ,COSTING_METHOD
    ,COST
    ,LAST_PURCHASE_PRICE
    ,AVERAGE_COST
    ,TOTAL_QUANTITY_ON_HAND
    ,TOTAL_VALUE
    ,SALEUNIT
    ,STOCK_UNIT
    ,SHIPPING_COST
    ,VENDOR_NAME
    ,MANUFACTURER
    ,MAXIMUN_QUANTITY
    ,WEIGHT
    ,IS_FUL_FILLABLE
    ,CAST(IS_INACTIVE AS VARCHAR) AS IS_INACTIVE
    ,CREATED_DATE
    ,LAST_MODIFIED_DATE
    ,'NETSUITE' AS SOURCESYSTEM,
    'PLAYFLY' AS COMPANY,
     CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS CONSOLIDATED_GOLD_LOAD_DATE
from {{ env_var('DBT_PLAYFLY', 'playfly_dev') }}.gold.NETSUITE_DIM_ITEM

union all

select
    CAST(ITEM_ID AS STRING) AS ITEM_ID,
    CAST(NULL AS STRING) AS ITEM_FULL_NAME,
    CAST(ITEM_NAME AS STRING) AS ITEM_NAME,
    CAST(ITEM_NAME AS STRING) AS DISPLAY_NAME,
    CAST(DESCRIPTION AS STRING) AS DESCRIPTION,
    CAST(NULL AS STRING) AS STORE_DISPLAY_NAME,
    CAST(NULL AS STRING) AS STORE_DESCRIPTION,
    CAST(NULL AS STRING) AS STORE_DETAILED_DESCRIPTION,
    CAST(ITEM_TYPE AS STRING) AS ITEM_TYPE,
    CAST(NULL AS STRING) AS SUB_TYPE,
    CAST(NULL AS NUMBER) AS CLASS_ID,
    CAST(NULL AS NUMBER) AS DEPARTMENT_ID,
    CAST(NULL AS NUMBER) AS LOCATION_ID,
    CAST(NULL AS NUMBER) AS SUBSIDIARY,
    CAST(NULL AS NUMBER) AS PARENT,
    CAST(NULL AS NUMBER) AS PRICING_GROUP,
    CAST(NULL AS NUMBER) AS UNITS_TYPE,
    CAST(NULL AS NUMBER) AS INCOME_ACCOUNT,
    CAST(COSTING_METHOD AS STRING) AS COSTING_METHOD,
    COST AS COST,
    CAST(NULL AS FLOAT) AS LAST_PURCHASE_PRICE,
    CAST(NULL AS FLOAT) AS AVERAGE_COST,
    CAST(NULL AS FLOAT) AS TOTAL_QUANTITY_ON_HAND,
    CAST(NULL AS FLOAT) AS TOTAL_VALUE,
    CAST(NULL AS NUMBER) AS SALEUNIT,
    CAST(NULL AS NUMBER) AS STOCK_UNIT,
    CAST(NULL AS FLOAT) AS SHIPPING_COST,
    CAST(NULL AS STRING) AS VENDOR_NAME,
    CAST(NULL AS STRING) AS MANUFACTURER,
    CAST(NULL AS NUMBER) AS MAXIMUN_QUANTITY,
    CAST(NULL AS FLOAT) AS WEIGHT,
    CAST(NULL AS BOOLEAN) AS IS_FUL_FILLABLE,
    CAST(IS_INACTIVE AS VARCHAR) AS IS_INACTIVE,
    CAST(CREATED_DATE AS TIMESTAMP_NTZ) AS CREATED_DATE,
    CAST(LAST_MODIFIED_DATE AS TIMESTAMP_NTZ) AS LAST_MODIFIED_DATE
    ,'SAGE' AS SOURCESYSTEM,
    'SPOTLESS' AS COMPANY,
     CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS CONSOLIDATED_GOLD_LOAD_DATE
from {{ env_var('DBT_SPOTLESS', 'spotless_dev') }}.gold.SAGE_DIM_ITEM