{{ config(
    materialized = 'incremental',
    incremental_strategy = 'merge',
    unique_key = ['DEPARTMENT_ID','SOURCESYSTEM','COMPANY']
) }}

select
    DEPARTMENT_ID,
    DEPARTMENT_NAME,
    DEPARTMENT_FULL_NAME,
    PARENT,
    TO_VARCHAR(IS_INACTIVE) AS IS_INACTIVE,
    LAST_MODIFIED_DATE,
    'NETSUITE' AS SOURCESYSTEM,
    'WAGWAY' AS COMPANY,
     CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS CONSOLIDATED_GOLD_LOAD_DATE
from {{ env_var('DBT_WAGWAY', 'wagway_dev') }}.gold.NETSUITE_DIM_DEPARTMENT

union all

select
    DEPARTMENT_ID,
    DEPARTMENT_NAME,
    DEPARTMENT_FULL_NAME,
    PARENT,
    TO_VARCHAR(IS_INACTIVE) AS IS_INACTIVE,
    LAST_MODIFIED_DATE,
    'NETSUITE' AS SOURCESYSTEM,
    'PLAYFLY' AS COMPANY,
     CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS CONSOLIDATED_GOLD_LOAD_DATE
from {{ env_var('DBT_PLAYFLY', 'playfly_dev') }}.gold.NETSUITE_DIM_DEPARTMENT

union all

select
    DIM_DEPARTMENT_ID AS DEPARTMENT_ID,
    DEPARTMENT_ID AS DEPARTMENT_NAME,
    DEPARTMENT_NAME AS DEPARTMENT_FULL_NAME,
    PARENT_ID AS PARENT,
    TO_VARCHAR(IS_INACTIVE) AS IS_INACTIVE,
    LAST_MODIFIED_DATE,
    'SAGE' AS SOURCESYSTEM,
    'SPOTLESS' AS COMPANY,
     CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS CONSOLIDATED_GOLD_LOAD_DATE
from {{ env_var('DBT_SPOTLESS', 'spotless_dev') }}.gold.SAGE_DIM_DEPARTMENT