SELECT 
    DISTINCT 
    HASH(PRIMARY_CITY , STATE_CODE) AS DIM_LOCATION_ID,
    PRIMARY_CITY AS CITY,
    STATE_CODE,
    STATE_NAME AS STATE,
FROM 
 {{ source('macro_silver', 'location') }}  
WHERE PRIMARY_CITY IS NOT NULL