{{ config(
    materialized = 'table',
    alias = 'rpt_transaction_summary'

) }}

SELECT
    COMPANY,
    SOURCESYSTEM,
    DIM_SUBSIDIARY_ID,
    DIM_DEPARTMENT_ID,
    DIM_LOCATION_ID,
    DIM_CLASS_ID,
    DIM_ITEM_ID,
    DIM_CHART_OF_ACCOUNT_ID,
    ACCOUNT_NUMBER,
    ACCOUNT_NAME,
    ACCOUNT_TYPE,
    DIM_PERIOD_ID,
    POSTING_PERIOD_DATE,
    CURRENCY,
    METRIC_L1,
    METRIC_L2,
    METRIC_L3,
    METRIC_L4,
    METRIC_L5,
    METRIC_L6,
    SUM(NETAMOUNT) AS TOTAL_NET_AMOUNT,
    SUM(AMOUNT) AS TOTAL_AMOUNT,
    SUM(CONVERTED_NET_AMOUNT) AS TOTAL_CONVERTED_NET_AMOUNT,
    SUM(BOM_QUANTITY) AS TOTAL_BOM_QUANTITY,
    SUM(QUANTITY) AS TOTAL_QUANTITY

FROM {{ env_var('DBT_CONSOLIDATED') }}.GOLD.FACT_TRANSACTION
GROUP BY
    COMPANY,
    SOURCESYSTEM,
    DIM_SUBSIDIARY_ID,
    DIM_DEPARTMENT_ID,
    DIM_LOCATION_ID,
    DIM_CLASS_ID,
    DIM_ITEM_ID,
    DIM_CHART_OF_ACCOUNT_ID,
    ACCOUNT_NUMBER,
    ACCOUNT_NAME,
    ACCOUNT_TYPE,
    DIM_PERIOD_ID,
    POSTING_PERIOD_DATE,
    CURRENCY,
    METRIC_L1,
    METRIC_L2,
    METRIC_L3,
    METRIC_L4,
    METRIC_L5,
    METRIC_L6
