{{ config(
    materialized = 'table',
    alias = 'rpt_transaction_summary'

) }}

SELECT
    COMPANY,
    SOURCESYSTEM,
    DIM_SUBSIDIARY_ID,
    DIM_DEPARTMENT_ID,
    DIM_LOCATION_ID,
    DIM_CLASS_ID,
    DIM_ITEM_ID,
    DIM_PROJECT_ID,
    DIM_ADDBACK_ID,
    DIM_CHART_OF_ACCOUNT_ID,
    ACCOUNT_NUMBER,
    ACCOUNT_NAME,
    ACCOUNT_TYPE,
    ADJ_TYPE,
    DIM_PERIOD_ID,
    MAX(PERIOD_START_DATE) AS PERIOD_START_DATE,
    SUM(NETAMOUNT*-1) AS TOTAL_NET_AMOUNT,
    SUM(AMOUNT*-1) AS TOTAL_AMOUNT,
    SUM(AMOUNT_UNCONVERTED*-1) AS TOTAL_AMOUNT_UNCONVERTED,
    SUM(CONVERTED_NET_AMOUNT*-1) AS TOTAL_CONVERTED_NET_AMOUNT,
    SUM(BOM_QUANTITY) AS TOTAL_BOM_QUANTITY,
    SUM(QUANTITY) AS TOTAL_QUANTITY

FROM {{ env_var('DBT_CONSOLIDATED') }}.GOLD.FACT_TRANSACTION
GROUP BY
    ALL
