{% set company = var('company') %}
{{ config(enabled = var('sourcesystem', 'none') in ['hubspot', 'hubspot_pawville']) }}
{{ config(
    enabled = false,
    database = get_target_database(company),
    alias = 'dim_contact',
    materialized = 'incremental',
    incremental_strategy = 'merge',
    unique_key = ['ID','SOURCE_SCHEMA']
) }}

SELECT
    ID,
    PROPERTY_FIRSTNAME AS FIRST_NAME,

    {% if company | lower == 'amh' %}
        PROPERTY_MIDDLE_NAME AS MIDDLE_NAME,
    {% endif %}

    PROPERTY_LASTNAME AS LAST_NAME,
    PROPERTY_EMAIL AS EMAIL,
    PROPERTY_PHONE AS PHONE,
    PROPERTY_MOBILEPHONE AS MOBILE_PHONE,
    PROPERTY_LIFECYCLESTAGE AS LIFECYCLE_STAGE,
    PROPERTY_HUBSPOT_OWNER_ID AS OWNER_ID,
    PROPERTY_JOBTITLE AS JOBTITLE,
    PROPERTY_CREATEDATE AS CREATE_DATE ,
    PROPERTY_HS_LEAD_STATUS AS LEAD_STATUS,
    PROPERTY_ADDRESS AS ADDRESS,
    PROPERTY_CITY AS CITY,
    PROPERTY_STATE AS STATE,
    PROPERTY_COUNTRY AS COUNTRY,
    PROPERTY_FAX AS FAX,
    PROPERTY_HS_TIMEZONE AS TIMEZONE,
    --PROPERTY_COMPANY AS COMPANY,
    --PROPERTY_HS_LASTMODIFIEDDATE AS LAST_MODIFIED_DATE,
    'HUBSPOT' AS SOURCE_SCHEMA


FROM {{ get_silver_source(company , 'HUBSPOT_CONTACT') }} 


{% if company == 'wagway'%} 
UNION ALL 

SELECT
    ID,
    PROPERTY_FIRSTNAME AS FIRST_NAME,
    PROPERTY_LASTNAME AS LAST_NAME,
    PROPERTY_EMAIL AS EMAIL,
    PROPERTY_PHONE AS PHONE,
    PROPERTY_MOBILEPHONE AS MOBILE_PHONE,
    PROPERTY_LIFECYCLESTAGE AS LIFECYCLE_STAGE,
    PROPERTY_HUBSPOT_OWNER_ID AS OWNER_ID,
    PROPERTY_JOBTITLE AS JOBTITLE,
    PROPERTY_CREATEDATE AS CREATE_DATE ,
    PROPERTY_HS_LEAD_STATUS AS LEAD_STATUS,
    PROPERTY_ADDRESS AS ADDRESS,
    PROPERTY_CITY AS CITY,
    PROPERTY_STATE AS STATE,
    PROPERTY_COUNTRY AS COUNTRY,
    PROPERTY_FAX AS FAX,
    PROPERTY_HS_TIMEZONE AS TIMEZONE,
    --PROPERTY_COMPANY AS COMPANY,
    --PROPERTY_LASTMODIFIEDDATE AS LAST_MODIFIED_DATE,
    'HUBSPOT_PAWVILLE' AS SOURCE_SCHEMA
FROM {{ get_silver_source(company, 'HUBSPOT_PAWVILLE_CONTACT') }} 
{% endif %}