{% set company = var('company') %}
{{ config(enabled = var('sourcesystem', 'none') in ['hubspot', 'hubspot_pawville']) }}

{{ config(
    enabled = false,
    database = get_target_database(company),
    alias = 'dim_deal',
    materialized = 'incremental',
    incremental_strategy = 'merge',
    unique_key = ['DIM_DEAL_ID','SOURCE_SCHEMA']
) }}

SELECT
    DEAL_ID AS DIM_DEAL_ID, 
    PROPERTY_DEALNAME AS DEAL_NAME,
    PROPERTY_AMOUNT AS AMOUNT,
    DEAL_PIPELINE_ID AS PIPELINE_ID,
    DEAL_PIPELINE_STAGE_ID AS STAGE_ID,
    PROPERTY_CLOSEDATE AS CLOSE_DATE,
    PROPERTY_CREATEDATE AS CREATE_DATE,
    PROPERTY_HS_CREATEDATE AS HS_CREATE,
    PROPERTY_HS_LASTMODIFIEDDATE AS HS_LAST_MODIFIED_DATE,
    OWNER_ID,
    PROPERTY_DEALTYPE AS DEAL_TYPE,
    PROPERTY_HS_FORECAST_AMOUNT AS HS_FORECAST_AMOUNT,
    PROPERTY_HS_DEAL_STAGE_PROBABILITY AS HS_DEAL_STAGE_PROBABILITY,
    
    {% if company | lower != 'amh' %}
        TRIM(PROPERTY_DESCRIPTION) AS PROPERTY_DESCRIPTION,
    {% endif %}
    
    'HUBSPOT' AS SOURCE_SCHEMA
FROM {{ get_silver_source(company, 'HUBSPOT_DEAL') }}

{% if company == 'wagway' %}

UNION ALL

SELECT
    DEAL_ID AS DIM_DEAL_ID, 
    PROPERTY_DEALNAME AS DEAL_NAME,
    PROPERTY_AMOUNT AS AMOUNT,
    DEAL_PIPELINE_ID AS PIPELINE_ID,
    DEAL_PIPELINE_STAGE_ID AS STAGE_ID,
    PROPERTY_CLOSEDATE AS CLOSE_DATE,
    PROPERTY_CREATEDATE AS CREATE_DATE,
    PROPERTY_HS_CREATEDATE AS HS_CREATE,
    PROPERTY_HS_LASTMODIFIEDDATE AS HS_LAST_MODIFIED_DATE,
    OWNER_ID,
    PROPERTY_DEALTYPE AS DEAL_TYPE,
    PROPERTY_HS_FORECAST_AMOUNT AS HS_FORECAST_AMOUNT,
    PROPERTY_HS_DEAL_STAGE_PROBABILITY AS HS_DEAL_STAGE_PROBABILITY,
    PROPERTY_DESCRIPTION,
    'HUBSPOT_PAWVILLE' AS SOURCE_SCHEMA
FROM {{ get_silver_source(company, 'HUBSPOT_PAWVILLE_DEAL') }}

{% endif %}