{% set company = var('company') %}
{% set sourcesystem = var('sourcesystem') %}

{{ config(
    enabled = (var('company') | lower) == 'wagway'
        and (var('sourcesystem') | lower) == 'gingr'
) }}

{{ config(
    database = get_target_database(var('company')),
    materialized = 'incremental',
    incremental_strategy = 'merge',
    unique_key = ['ID','SOURCE_DB']
) }}

with raw as 
(
    select *
    from {{ get_raw_source(company, sourcesystem, 'OWNERS') }}

    {% if is_incremental() %}
        where ODS_LAST_UPDATE_DATE > (
            select dateadd(
                day,
                -1,
                coalesce(max(t.ODS_LAST_UPDATE_DATE), '1900-01-01'::timestamp_ntz)
            )
            from {{ this }} t
        )
    or _FIVETRAN_DELETED = true
    {% endif %}
),

cleaned as 
(
    select
        CAST(TRIM(ID) AS BIGINT) AS ID,
        TRIM(SOURCE_DB) AS SOURCE_DB,
        TRIM(FIRST_NAME) AS FIRST_NAME,
        TRIM(LAST_NAME) AS LAST_NAME,
        TRIM(ADDRESS_1) AS ADDRESS_1,
        TRIM(ADDRESS_2) AS ADDRESS_2,
        TRIM(CITY) AS CITY,
        TRIM(STATE) AS STATE,
        TRIM(ZIP) AS ZIP,
        TRIM(EMAIL) AS EMAIL,
        TRIM(HOME_PHONE) AS HOME_PHONE,
        TRIM(CELL_PHONE) AS CELL_PHONE,
        TRIM(EMERGENCY_CONTACT_NAME) AS EMERGENCY_CONTACT_NAME,
        TRIM(EMERGENCY_CONTACT_PHONE) AS EMERGENCY_CONTACT_PHONE,
        TRIM(NOTES) AS NOTES,
        CAST(TRIM(DEFAULT_PAYMENT_METHOD_FK) AS BIGINT) AS DEFAULT_PAYMENT_METHOD_FK,
        CAST(TRIM(HOME_LOCATION) AS BIGINT) AS HOME_LOCATION,
        CAST(TRIM(OPT_OUT_EMAIL) AS BOOLEAN) AS OPT_OUT_EMAIL,
        CAST(TRIM(OPT_OUT_SMS) AS BOOLEAN) AS OPT_OUT_SMS,
        CAST(TRIM(OPT_OUT_MARKETING_EMAIL) AS BOOLEAN) AS OPT_OUT_MARKETING_EMAIL,
        CAST(TRIM(OPT_OUT_MARKETING_SMS) AS BOOLEAN) AS OPT_OUT_MARKETING_SMS,
        CAST(TRIM(OPT_OUT_PHOTO_SHARING) AS BOOLEAN) AS OPT_OUT_PHOTO_SHARING,
        CAST(TRIM(OPT_OUT_REMINDER_EMAIL) AS BOOLEAN) AS OPT_OUT_REMINDER_EMAIL,
        CAST(TRIM(OPT_OUT_REMINDER_SMS) AS BOOLEAN) AS OPT_OUT_REMINDER_SMS,
        CAST(TRIM(CURRENT_BALANCE) AS FLOAT) AS CURRENT_BALANCE,
        TRIM(LATITUDE) AS LATITUDE,
        TRIM(LONGITUDE) AS LONGITUDE,
        TRIM(STRIPE_CUSTOMER_ID) AS STRIPE_CUSTOMER_ID,
        TRIM(GINGR_PAYMENTS_CUSTOMER_ID) AS GINGR_PAYMENTS_CUSTOMER_ID,
        TRIM(GINGR_PAYMENTS_PRIMARY_CARD) AS GINGR_PAYMENTS_PRIMARY_CARD,
        TRIM(STRIPE_DEFAULT_CARD) AS STRIPE_DEFAULT_CARD,
        CAST(TRIM(PAYMENT_PROCESSOR_ID) AS BIGINT) AS PAYMENT_PROCESSOR_ID,
        TRIM(PASSWORD) AS PASSWORD,
        TRIM(KEY) AS KEY,
        TRIM(BARCODE) AS BARCODE,
        CAST(TRIM(ALLOW_ONLINE_LOGIN) AS BOOLEAN) AS ALLOW_ONLINE_LOGIN,
        CAST(TRIM(CREATED_AT) AS TIMESTAMP_NTZ) AS CREATED_AT,
        CAST(TRIM(CREATED_BY) AS BIGINT) AS CREATED_BY,
        TRIM(KL_OWNER_ID) AS KL_OWNER_ID,
        TRIM(FORM_TOKEN) AS FORM_TOKEN,
        CAST(TRIM(OPT_OUT_REWARDS) AS BOOLEAN) AS OPT_OUT_REWARDS,
        TRIM(SIGNED_AGREEMENTS) AS SIGNED_AGREEMENTS,
        CAST(TRIM(SOURCE) AS BIGINT) AS SOURCE,
        CAST(TRIM(ROVER_CUSTOMER) AS BOOLEAN) AS ROVER_CUSTOMER,
        CAST(TRIM(ROVER_CUSTOMER_CREATED_DATE) AS TIMESTAMP_NTZ) AS ROVER_CUSTOMER_CREATED_DATE,
        TRIM(MD5_HASH) AS MD5_HASH,        
        TRIM(DELETE_INDICATOR) AS DELETE_INDICATOR,
        CAST(TRIM(_FIVETRAN_DELETED) AS BOOLEAN) AS _FIVETRAN_DELETED,
        CAST(TRIM(_FIVETRAN_SYNCED) AS TIMESTAMP_TZ) AS _FIVETRAN_SYNCED,
        CAST(TRIM(ODS_LAST_UPDATE_DATE) AS TIMESTAMP_NTZ) AS ODS_LAST_UPDATE_DATE,
        CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE
    from raw
)

select * from cleaned