{{
    config(
        materialized="incremental",
        unique_key="EMPLOYEE_ID",
        incremental_strategy="merge",
    )
}}

SELECT
    CAST(ID AS INT) AS EMPLOYEE_ID,
    TRIM(ENTITYID) AS ENTITY_ID,
    ACCOUNTNUMBER AS ACCOUNT_NUMBER,
    EMPLOYEETYPE AS EMPLOYEE_TYPE_ID,
    TRIM(TITLE) AS TITLE,
    TRIM(EMAIL) AS EMAIL,
    TRIM(JOBDESCRIPTION) AS JOB_DESCRIPTION,
    CAST(CLASS AS INT) AS CLASS_ID,
    CAST(DEPARTMENT AS INT) AS DEPARTMENT_ID,
    CAST(LOCATION AS INT) AS LOCATION_ID,
    CAST(CURRENCY AS INT) AS CURRENCY,
    CAST(SUBSIDIARY AS INT) AS SUBSIDIARY_ID,
    CAST(DATECREATED AS DATE) AS DATE_CREATED,
    CAST(
        CASE 
            WHEN ISINACTIVE = 'T' THEN TRUE
            WHEN ISINACTIVE = 'F' THEN FALSE
            ELSE NULL
        END AS BOOLEAN
    ) AS IS_INACTIVE,
    CAST(LASTMODIFIEDDATE AS TIMESTAMP_NTZ) AS LAST_MODIFIED_DATE,
    _FIVETRAN_DELETED AS IS_DELETED,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE

FROM {{ source("wagway_netsuite", "EMPLOYEE") }}

{% if is_incremental() %}
WHERE CAST(LASTMODIFIEDDATE AS TIMESTAMP_NTZ) > (
    SELECT COALESCE(MAX(LAST_MODIFIED_DATE), '1900-01-01'::TIMESTAMP_NTZ)
    FROM {{ this }}
)
{% endif %}
