{{ config(
    materialized = 'incremental',
    unique_key = 'LOCATION_ID',
    incremental_strategy = 'merge'
) }}

SELECT
    CAST(ID AS INT) AS LOCATION_ID,
    TRIM(NAME) AS LOCATION_NAME,
    TRIM(FULLNAME) AS LOCATION_FULL_NAME,
    TRIM(LOCATIONTYPE) AS LOCATION_TYPE,
    CAST(PARENT AS INT) AS PARENT,
    CAST(SUBSIDIARY AS INT) AS SUBSIDIARY_ID,
    CAST(LATITUDE AS FLOAT) AS LATITUDE,
    CAST(LONGITUDE AS FLOAT) AS LONGITUDE,
    CAST(
        CASE 
            WHEN ISINACTIVE = 'T' THEN TRUE
            WHEN ISINACTIVE = 'F' THEN FALSE
            ELSE NULL
        END AS BOOLEAN
    ) AS IS_INACTIVE,
    CAST(LASTMODIFIEDDATE AS TIMESTAMP_NTZ) AS LAST_MODIFIED_DATE,
    _FIVETRAN_DELETED AS IS_DELETED,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE

FROM {{ source('wagway_netsuite', 'LOCATION') }}

{% if is_incremental() %}
WHERE CAST(LASTMODIFIEDDATE AS TIMESTAMP_NTZ) > (
    SELECT COALESCE(MAX(LAST_MODIFIED_DATE), '1900-01-01'::TIMESTAMP_NTZ)
    FROM {{ this }}
)
{% endif %}
