{{ config(
    materialized = 'incremental',
    unique_key = 'ITEM_ID',
    incremental_strategy = 'merge'
) }}

SELECT
    CAST(ID AS INT) AS ITEM_ID,
    TRIM(ITEMID) AS ITEM_CODE,
    TRIM(DISPLAYNAME) AS DISPLAY_NAME,
    TRIM(FULLNAME) AS FULL_NAME,
    TRIM(DESCRIPTION) AS DESCRIPTION,
    TRIM(STOCKDESCRIPTION) AS STOCK_DESCRIPTION,
    TRIM(ITEMTYPE) AS ITEM_TYPE,
    TRIM(SUBTYPE) AS SUB_TYPE,
    TRIM(MANUFACTURER) AS MANUFACTURER,
    TRIM(VENDORNAME) AS VENDOR_NAME,
    CAST(CLASS AS INT) AS CLASS_ID,
    CAST(DEPARTMENT AS INT) AS DEPARTMENT_ID,
    CAST(LOCATION AS INT) AS LOCATION_ID,
    CAST(PARENT AS INT) AS PARENT_ID,
    CAST(PRICINGGROUP AS INT) AS PRICING_GROUP_ID,
    CAST(SALEUNIT AS INT) AS SALE_UNIT_ID,
    CAST(STOCKUNIT AS INT) AS STOCK_UNIT_ID,
    CAST(UNITSTYPE AS INT) AS UNITS_TYPE_ID,
    CAST(SUBSIDIARY AS INT) AS SUBSIDIARY_ID,
    CAST(INCOMEACCOUNT AS INT) AS INCOME_ACCOUNT_ID,
    CAST(AVERAGECOST AS FLOAT) AS AVERAGE_COST,
    CAST(COST AS FLOAT) AS COST,
    TRIM(COSTINGMETHOD) AS COSTING_METHOD,
    CAST(LASTPURCHASEPRICE AS FLOAT) AS LAST_PURCHASE_PRICE,
    CAST(SHIPPINGCOST AS FLOAT) AS SHIPPING_COST,
    CAST(TOTALVALUE AS FLOAT) AS TOTAL_VALUE,
    CAST(QUANTITYAVAILABLE AS FLOAT) AS QUANTITY_AVAILABLE,
    CAST(MAXIMUMQUANTITY AS FLOAT) AS MAXIMUM_QUANTITY,
    CAST(WEIGHT AS FLOAT) AS WEIGHT,
    CAST(
        CASE 
            WHEN ISFULFILLABLE = 'T' THEN TRUE
            WHEN ISFULFILLABLE = 'F' THEN FALSE
            ELSE NULL
        END AS BOOLEAN
    ) AS IS_FULFILLABLE,
    CAST(
        CASE 
            WHEN ISINACTIVE = 'T' THEN TRUE
            WHEN ISINACTIVE = 'F' THEN FALSE
            ELSE NULL
        END AS BOOLEAN
    ) AS IS_INACTIVE,
    CAST(CREATEDDATE AS TIMESTAMP_NTZ) AS CREATED_DATE,
    CAST(LASTMODIFIEDDATE AS TIMESTAMP_NTZ) AS LAST_MODIFIED_DATE,
    _FIVETRAN_DELETED AS IS_DELETED,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE

FROM {{ source('wagway_netsuite', 'ITEM') }}

{% if is_incremental() %}
WHERE CAST(LASTMODIFIEDDATE AS TIMESTAMP_NTZ) > (
    SELECT COALESCE(MAX(LAST_MODIFIED_DATE), '1900-01-01'::TIMESTAMP_NTZ)
    FROM {{ this }}
)
{% endif %}
