{{ config(
    materialized = 'incremental',
    unique_key = ['TRANSACTION_ID', 'TRANSACTION_LINE_ID'],
    incremental_strategy = 'merge'
) }}

SELECT
    CAST(TRANSACTION AS INT) AS TRANSACTION_ID,
    CAST(TRANSACTIONLINE AS INT) AS TRANSACTION_LINE_ID,
    CAST(ACCOUNT AS INT) AS ACCOUNT_ID,
    CAST(ACCOUNTINGBOOK AS INT) AS ACCOUNTING_BOOK_ID,
    TRIM(ACCOUNTTYPE) AS ACCOUNT_TYPE,
    TRIM(POSTING) AS TRANSACTION_ACCOUNTING_POSTING_FLAG,
    CAST(AMOUNT AS FLOAT) AS AMOUNT,
    CAST(NETAMOUNT AS FLOAT) AS NET_AMOUNT,
    CAST(AMOUNTPAID AS FLOAT) AS AMOUNT_PAID,
    CAST(AMOUNTUNPAID AS FLOAT) AS AMOUNT_UN_PAID,
    CAST(EXCHANGERATE AS FLOAT) AS EXCHANGE_RATE,
    CAST(LASTMODIFIEDDATE AS TIMESTAMP_NTZ) AS LAST_MODIFIED_DATE,
    _FIVETRAN_DELETED AS IS_DELETED,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE

FROM {{ source('wagway_netsuite', 'TRANSACTIONACCOUNTINGLINE') }}

{% if is_incremental() %}
WHERE CAST(LASTMODIFIEDDATE AS TIMESTAMP_NTZ) > (
    SELECT COALESCE(MAX(LAST_MODIFIED_DATE), '1900-01-01'::TIMESTAMP_NTZ)
    FROM {{ this }}
)
{% endif %}
