{{ config(
    materialized = 'incremental',
    unique_key = 'TRANSACTION_ID',
    incremental_strategy = 'merge'
) }}

SELECT
    CAST(ID AS INT) AS TRANSACTION_ID,
    TRANSACTIONNUMBER AS TRANSACTION_NUMBER,
    TRIM(TRANID) AS TRANS_ID,
    TRIM(TYPE) AS TRANSACTION_TYPE,
    TRIM(STATUS) AS TRANSACTION_STATUS_ID,
    TRIM(BILLINGSTATUS) AS BILLING_STATUS,
    TRIM(SOURCE) AS SOURCE,
    TRIM(TITLE) AS TITLE,
    CAST(POSTINGPERIOD AS INT) AS POSTING_PERIOD_ID,
    CAST(ENTITY AS INT) AS INTERNAL_ENTITY_ID,
    CAST(EMPLOYEE AS INT) AS EMPLOYEE_ID,
    CAST(PAYMENTMETHOD AS INT) AS PAYMENT_METHOD_ID,
    CAST(CURRENCY AS INT) AS CURRENCY_ID,
    CAST(SOURCETRANSACTION AS INT) AS SOURCE_TRANSACTION,
    CAST(AMOUNTUNBILLED AS FLOAT) AS AMOUNT_UNBILLED,
    CAST(EXCHANGERATE AS FLOAT) AS EXCHANGE_RATE,
    CAST(TRANDATE AS DATE) AS TRAN_DATE,
    CAST(CREATEDDATE AS DATE) AS CREATED_DATE,
    CAST(STARTDATE AS DATE) AS START_DATE,
    CAST(ENDDATE AS DATE) AS END_DATE,
    CAST(CLOSEDATE AS DATE) AS CLOSE_DATE,
    CAST(DUEDATE AS DATE) AS DUE_DATE,
    CAST(LASTMODIFIEDDATE AS TIMESTAMP_NTZ) AS LAST_MODIFIED_DATE,
    TRIM(BILLINGADDRESS) AS BILLING_ADDRESS_ID,
    TRIM(SHIPPINGADDRESS) AS SHIPPING_ADDRESS_ID,
    TRIM(EMAIL) AS SESSION_SHOP_EMAIL,
    TRIM(MEMO) AS MEMO,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE

FROM {{ source('wagway_netsuite', 'TRANSACTION') }}

{% if is_incremental() %}
WHERE CAST(LASTMODIFIEDDATE AS TIMESTAMP_NTZ) > (
    SELECT COALESCE(MAX(LAST_MODIFIED_DATE), '1900-01-01'::TIMESTAMP_NTZ)
    FROM {{ this }}
)
{% endif %}
