{{ config(
    materialized = 'incremental',
    unique_key = 'ACCOUNT_ID',
    incremental_strategy = 'merge'
) }}

SELECT 
    CAST(ID AS INT) AS ACCOUNT_ID,
    ACCTNUMBER AS ACCOUNT_NUMBER,
    CAST(CLASS AS INT) AS CLASS_ID,
    CAST(CURRENCY AS INT) AS CURRENCY_ID,
    CAST(LASTMODIFIEDDATE AS DATE) AS LAST_MODIFIED_DATE,
    CAST(DEPARTMENT AS INT) AS DEPARTMENT_ID,
    DESCRIPTION AS ACCOUNT_DESCRIPTION,
    ACCOUNTSEARCHDISPLAYNAME AS DISPLAY_NAME,
    DISPLAYNAMEWITHHIERARCHY AS DISPLAY_NAME_WITH_HIERARCHY,
    ISINACTIVE AS IS_INACTIVE,
    CAST(LOCATION AS INT) AS LOCATION_ID,
    FULLNAME AS ACCOUNT_NAME,
    CAST(PARENT AS INT) AS PARENT_ID,
    SUBSIDIARY AS SUBSIDIARY_ID,
    ACCTTYPE AS ACCOUNT_TYPE,
    CURRENT_TIMESTAMP() AS SILVER_LOAD_DATE
FROM {{ source('wagway_netsuite', 'ACCOUNT') }}