{{ config(
    materialized = 'incremental',
    unique_key = 'CURRENCY_RATE_ID',
    incremental_strategy = 'merge'
) }}

SELECT
    CAST(ID AS INT) AS CURRENCY_RATE_ID,
    CAST(EFFECTIVEDATE AS DATE) AS EFFECTIVE_DATE,
    CAST(LASTMODIFIEDDATE AS DATE) AS LAST_MODIFIED_DATE,
    CAST(EXCHANGERATE AS FLOAT) AS EXCHANGE_RATE,
    EXTERNALID AS EXTERNAL_ID,
    CAST(TRANSACTIONCURRENCY AS INT) AS TRANSACTION_CURRENCY,
    CURRENT_TIMESTAMP() AS SILVER_LOAD_DATE
FROM {{ source('wagway_netsuite', 'CURRENCYRATE') }}
