{{ config(
    materialized = 'incremental',
    unique_key = 'POSTING_PERIOD_ID',
    incremental_strategy = 'merge'
) }}

SELECT
    TRY_CAST(ID AS INT) AS POSTING_PERIOD_ID,
    TRIM(PERIODNAME) AS PERIOD_NAME,
    TRY_CAST("YEAR" AS INT) AS YEAR,
    CAST(STARTDATE AS TIMESTAMP_NTZ) AS START_DATE,
    CAST(ENDDATE AS TIMESTAMP_NTZ) AS END_DATE,
    CAST(CLOSEDONDATE AS DATE) AS CLOSED_ON_DATE,
    CAST(LASTMODIFIEDDATE AS TIMESTAMP_NTZ) AS LAST_MODIFIED_DATE,
    _FIVETRAN_DELETED AS IS_DELETED,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE

FROM {{ source('wagway_netsuite', 'ACCOUNTINGPERIOD') }}

{% if is_incremental() %}
WHERE CAST(LASTMODIFIEDDATE AS TIMESTAMP_NTZ) > (
    SELECT COALESCE(MAX(LAST_MODIFIED_DATE), '1900-01-01'::TIMESTAMP_NTZ)
    FROM {{ this }}
)
{% endif %}
