{{ config(
    materialized = 'incremental',
    unique_key = 'CURRENCY_RATE_ID',
    incremental_strategy = 'merge'
) }}

SELECT
    CAST(ID AS INT) AS CURRENCY_RATE_ID,
    CAST(TRANSACTIONCURRENCY AS INT) AS TRANSACTION_CURRENCY,
    CAST(EXCHANGERATE AS FLOAT) AS EXCHANGE_RATE,
    CAST(EFFECTIVEDATE AS DATE) AS EFFECTIVE_DATE,
    CAST(LASTMODIFIEDDATE AS DATE) AS LAST_MODIFIED_DATE,
    CURRENT_TIMESTAMP() AS SILVER_LOAD_DATE

FROM {{ source('wagway_netsuite', 'CURRENCYRATE') }}

{% if is_incremental() %}
WHERE CAST(LASTMODIFIEDDATE AS TIMESTAMP_NTZ) > (
    SELECT COALESCE(MAX(LAST_MODIFIED_DATE), '1900-01-01'::TIMESTAMP_NTZ)
    FROM {{ this }}
)
{% endif %}
