{{ config(
    materialized = 'incremental',
    unique_key = 'INTERNAL_ENTITY_ID',
    incremental_strategy = 'merge'
) }}

SELECT
    CAST(ID AS INT) AS INTERNAL_ENTITY_ID,
    TRIM(ENTITYID) AS ENTITY_ID,
    CAST(ENTITYNUMBER AS INT) AS ENTITY_NUMBER,
    TRIM("TYPE") AS ENTITY_TYPE,
    TRIM(ENTITYTITLE) AS ENTITY_TITLE,
    TRIM(FIRSTNAME) AS FIRST_NAME,
    TRIM(LASTNAME) AS LAST_NAME,
    TRIM(EMAIL) AS EMAIL,
    CAST(CUSTOMER AS INT) AS CUSTOMER_ID,
    CAST(VENDOR AS INT) AS VENDOR_ID,
    CAST(EMPLOYEE AS INT) AS EMPLOYEE_ID,
    CAST(CONTACT AS INT) AS CONTACT_ID,
    CAST("GROUP" AS INT) AS GROUP_ID,
    CAST(PARENT AS INT) AS PARENT_ID,
    CAST(
        CASE 
            WHEN ISPERSON = 'T' THEN TRUE
            WHEN ISPERSON = 'F' THEN FALSE
            ELSE NULL
        END AS BOOLEAN
    ) AS IS_PERSON,
    CAST(
        CASE 
            WHEN ISINACTIVE = 'T' THEN TRUE
            WHEN ISINACTIVE = 'F' THEN FALSE
            ELSE NULL
        END AS BOOLEAN
    ) AS IS_INACTIVE,
    CAST(DATECREATED AS DATE) AS DATE_CREATED,
    CAST(LASTMODIFIEDDATE AS TIMESTAMP_NTZ) AS LAST_MODIFIED_DATE,
    _FIVETRAN_DELETED AS IS_DELETED,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE

FROM {{ source('wagway_netsuite', 'ENTITY') }}

{% if is_incremental() %}
WHERE CAST(LASTMODIFIEDDATE AS TIMESTAMP_NTZ) > (
    SELECT COALESCE(MAX(LAST_MODIFIED_DATE), '1900-01-01'::TIMESTAMP_NTZ)
    FROM {{ this }}
)
{% endif %}
