{% set company = var('company', 'Unknown company') | lower %}
{% set sourcesystem = var('sourcesystem', 'Unknown source') | lower %}

{{ config(
    database = get_target_database(company),
    materialized = 'incremental',
    incremental_strategy = 'merge',
    unique_key = 'CUSTOMER_ID'
) }}

with source_data as (
    select *
    from {{ get_raw_source(company, sourcesystem, 'CUSTOMER') }}
    {% if is_incremental() %}
    where CAST(WHENMODIFIED AS TIMESTAMP_NTZ) > (
        select coalesce(max(WHEN_MODIFIED), '1900-01-01'::timestamp_ntz)
        from {{ this }}
    )
    or _FIVETRAN_DELETED = true
    {% endif %}
),

cleaned as (
    select
        -- Primary Key
        UPPER(TRIM(CUSTOMERID)) AS CUSTOMER_ID,

        -- Core Identifiers
        TRY_CAST(RECORDNO AS INT) AS RECORD_NO,
        TRIM(NAME) AS CUSTOMER_NAME,
        TRIM(ENTITY) AS ENTITY,
        TRIM(STATUS) AS STATUS,

        -- Accounts / Terms
        TRY_CAST(ACCOUNTKEY AS INT) AS ACCOUNT_KEY,
        TRY_CAST(ARACCOUNT AS INT) AS AR_ACCOUNT,
        TRIM(ARACCOUNTTITLE) AS AR_ACCOUNT_TITLE,
        TRIM(ARINVOICEPRINTTEMPLATEID) AS AR_INVOICE_PRINT_TEMPLATE_ID,
        TRIM(TERMNAME) AS TERM_NAME,
        TRY_CAST(TERMSKEY AS INT) AS TERMS_KEY,
        TRIM(TERMVALUE) AS TERM_VALUE,

        -- Customer Type
        TRIM(CUSTTYPE) AS CUSTOMER_TYPE,
        TRY_CAST(CUSTTYPEKEY AS INT) AS CUSTOMER_TYPE_KEY,

        -- Contact Info (Display Contact)
        TRIM(DISPLAYCONTACT_COMPANYNAME) AS DISPLAY_CONTACT_COMPANY_NAME,
        TRIM(DISPLAYCONTACT_CONTACTNAME) AS DISPLAY_CONTACT_NAME,
        TRIM(DISPLAYCONTACT_FIRSTNAME) AS DISPLAY_CONTACT_FIRST_NAME,
        TRIM(DISPLAYCONTACT_LASTNAME) AS DISPLAY_CONTACT_LAST_NAME,
        TRIM(DISPLAYCONTACT_INITIAL) AS DISPLAY_CONTACT_INITIAL,
        TRIM(DISPLAYCONTACT_EMAIL_1) AS DISPLAY_CONTACT_EMAIL_1,
        TRIM(DISPLAYCONTACT_EMAIL_2) AS DISPLAY_CONTACT_EMAIL_2,
        TRIM(DISPLAYCONTACT_CELLPHONE) AS DISPLAY_CONTACT_CELL_PHONE,
        TRIM(DISPLAYCONTACT_PHONE_1) AS DISPLAY_CONTACT_PHONE,
        TRIM(DISPLAYCONTACT_PRINTAS) AS DISPLAY_CONTACT_PRINT_AS,
        TRIM(DISPLAYCONTACT_STATUS) AS DISPLAY_CONTACT_STATUS,
        CAST(DISPLAYCONTACT_TAXABLE AS BOOLEAN) AS DISPLAY_CONTACT_TAXABLE,
        CAST(DISPLAYCONTACT_VISIBLE AS BOOLEAN) AS DISPLAY_CONTACT_VISIBLE,
        TRY_CAST(DISPLAYCONTACTKEY AS INT) AS DISPLAY_CONTACT_KEY,

        -- Contact Address
        TRIM(DISPLAYCONTACT_MAILADDRESS_ADDRESS_1) AS DISPLAY_CONTACT_ADDR_LINE_1,
        TRIM(DISPLAYCONTACT_MAILADDRESS_ADDRESS_2) AS DISPLAY_CONTACT_ADDR_LINE_2,
        TRIM(DISPLAYCONTACT_MAILADDRESS_ADDRESS_3) AS DISPLAY_CONTACT_ADDR_LINE_3,
        TRIM(DISPLAYCONTACT_MAILADDRESS_CITY) AS DISPLAY_CONTACT_CITY,
        TRIM(DISPLAYCONTACT_MAILADDRESS_STATE) AS DISPLAY_CONTACT_STATE,
        TRIM(DISPLAYCONTACT_MAILADDRESS_ZIP) AS DISPLAY_CONTACT_ZIP,
        TRIM(DISPLAYCONTACT_MAILADDRESS_COUNTRY) AS DISPLAY_CONTACT_COUNTRY,
        TRIM(DISPLAYCONTACT_MAILADDRESS_COUNTRYCODE) AS DISPLAY_CONTACT_COUNTRY_CODE,

        -- Mega Entity
        TRIM(MEGAENTITYID) AS MEGA_ENTITY_ID,
        TRY_CAST(MEGAENTITYKEY AS INT) AS MEGA_ENTITY_KEY,
        TRIM(MEGAENTITYNAME) AS MEGA_ENTITY_NAME,

        -- Territory
        TRIM(TERRITORYID) AS TERRITORY_ID,
        TRIM(TERRITORYKEY) AS TERRITORY_KEY,
        TRIM(TERRITORYNAME) AS TERRITORY_NAME,

        -- Financials
        TRY_CAST(TOTALDUE AS FLOAT) AS TOTAL_DUE,
        TRIM(PRCLST_OVERRIDE) AS PRCLST_OVERRIDE,
        TRIM(DELIVERY_OPTIONS) AS DELIVERY_OPTIONS,

        -- Flags
        CAST(EMAILOPTIN AS BOOLEAN) AS EMAIL_OPT_IN,
        CAST(ENABLEONLINEACHPAYMENT AS BOOLEAN) AS ENABLE_ONLINE_ACH_PAYMENT,
        CAST(ENABLEONLINECARDPAYMENT AS BOOLEAN) AS ENABLE_ONLINE_CARD_PAYMENT,
        CAST(ONETIME AS BOOLEAN) AS ONE_TIME,
        CAST(ONHOLD AS BOOLEAN) AS ON_HOLD,

        -- Dates
        CAST(LAST_INVOICEDATE AS DATE) AS LAST_INVOICE_DATE,
        CAST(LAST_STATEMENTDATE AS DATE) AS LAST_STATEMENT_DATE,
        CAST(WHENCREATED AS TIMESTAMP_NTZ) AS WHEN_CREATED,
        CAST(WHENMODIFIED AS TIMESTAMP_NTZ) AS WHEN_MODIFIED,

        -- Relationships
        TRY_CAST(CREATEDBY AS INT) AS CREATED_BY,
        TRIM(CREATEDBYLOGINID) AS CREATED_BY_LOGIN_ID,
        TRY_CAST(MODIFIEDBY AS INT) AS MODIFIED_BY,
        TRIM(MODIFIEDBYLOGINID) AS MODIFIED_BY_LOGIN_ID,

        -- Extra
        TRIM(OBJECTRESTRICTION) AS OBJECT_RESTRICTION,

        -- Flags / Deletes
        _FIVETRAN_DELETED AS IS_DELETED,

        -- Audit
        CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE
    from source_data
)

select *
from cleaned
