{% set company = var('company', 'Unknown company') | lower %}
{% set sourcesystem = var('sourcesystem', 'Unknown source') | lower %}
{{ config(enabled = var('sourcesystem', 'none') == 'sage') }}

{{ config(
    database = get_target_database(company),
    materialized = 'incremental',
    incremental_strategy = 'merge',
    unique_key = 'PROJECT_ID'
) }}

with source_data as (

    select *
    from {{ get_raw_source(company, sourcesystem, 'PROJECT') }}
    
    {% if is_incremental() %}
        where WHENMODIFIED > (
            select coalesce(max(WHEN_MODIFIED), '1900-01-01'::timestamp_ntz)
            from {{ this }}
        )
        or _FIVETRAN_DELETED = true
    {% endif %}

),

cleaned as (

   select
    -- Primary Key
    TRIM(PROJECTID) AS PROJECTID,

    -- Core Identifiers
    TRY_CAST(RECORDNO AS INT) AS RECORDNO,
    TRIM(RECORD_URL) AS RECORD_URL,
    TRIM(NAME) AS NAME,
    TRIM(DESCRIPTION) AS DESCRIPTION,
    TRIM(STATUS) AS STATUS,
    TRIM(PROJECTSTATUS) AS PROJECTSTATUS,
    TRY_CAST(PROJECTSTATUSKEY AS INT) AS PROJECTSTATUSKEY,
    TRIM(PROJECTCATEGORY) AS PROJECTCATEGORY,
    TRIM(PROJECTTYPE) AS PROJECTTYPE,
    TRY_CAST(PROJECTTYPEKEY AS INT) AS PROJECTTYPEKEY,

    -- Dates
    CAST(BEGINDATE AS DATE) AS BEGINDATE,
    CAST(PRJ_ESTIMATED_CLOSING_DATE AS DATE) AS PRJ_ESTIMATED_CLOSING_DATE,
    CAST(PRJ_TARGET_OPENING_DATE AS DATE) AS PRJ_TARGET_OPENING_DATE,
    CAST(WHENCREATED AS TIMESTAMP_NTZ) AS WHENCREATED,
    CAST(WHENMODIFIED AS TIMESTAMP_NTZ) AS WHENMODIFIED,

    -- Financials
    TRIM(BILLINGOVERMAX) AS BILLINGOVERMAX,
    TRIM(BILLINGPRICING) AS BILLINGPRICING,
    TRIM(EXPENSEPRICING) AS EXPENSEPRICING,
    EXPENSERATE AS EXPENSERATE,
    TRIM(POAPPRICING) AS POAPPRICING,
    POAPRATE AS POAPRATE,
    OBSPERCENTCOMPLETE AS OBSPERCENTCOMPLETE,
    TRIM(CURRENCY) AS CURRENCY,

    -- Flags
    CAST(BILLABLEAPPODEFAULT AS BOOLEAN) AS BILLABLEAPPODEFAULT,
    CAST(BILLABLEEXPDEFAULT AS BOOLEAN) AS BILLABLEEXPDEFAULT,
    CAST(EXCLUDEEXPENSES AS BOOLEAN) AS EXCLUDEEXPENSES,
    CAST(INVOICEWITHPARENT AS BOOLEAN) AS INVOICEWITHPARENT,
    CAST(PREVENTAPPO AS BOOLEAN) AS PREVENTAPPO,
    CAST(PREVENTEXPENSE AS BOOLEAN) AS PREVENTEXPENSE,
    CAST(PREVENTGENINVOICE AS BOOLEAN) AS PREVENTGENINVOICE,
    CAST(PREVENTTIMESHEET AS BOOLEAN) AS PREVENTTIMESHEET,
    CAST(WIPEXCLUDE AS BOOLEAN) AS WIPEXCLUDE,

    -- Hierarchy
    TRIM(PARENTID) AS PARENTID,
    TRY_CAST(PARENTKEY AS INT) AS PARENTKEY,
    TRIM(PARENTNAME) AS PARENTNAME,
    TRIM(ROOTPARENTID) AS ROOTPARENTID,
    TRY_CAST(ROOTPARENTKEY AS INT) AS ROOTPARENTKEY,
    TRIM(ROOTPARENTNAME) AS ROOTPARENTNAME,

    -- Class / Location
    TRIM(CLASSID) AS CLASSID,
    TRY_CAST(CLASSKEY AS INT) AS CLASSKEY,
    TRIM(CLASSNAME) AS CLASSNAME,
    TRIM(LOCATIONID) AS LOCATIONID,
    TRIM(LOCATIONNAME) AS LOCATIONNAME,
    TRY_CAST(PROJECTLOCATIONKEY AS INT) AS PROJECTLOCATIONKEY,

    -- Mega Entity / Location
    TRIM(MEGAENTITYID) AS MEGAENTITYID,
    TRY_CAST(MEGAENTITYKEY AS INT) AS MEGAENTITYKEY,
    TRIM(MEGAENTITYNAME) AS MEGAENTITYNAME,
    TRIM(MELOCATIONID) AS MELOCATIONID,
    TRY_CAST(MELOCATIONKEY AS INT) AS MELOCATIONKEY,
    TRIM(MELOCATIONNAME) AS MELOCATIONNAME,

    -- Relationships
    TRY_CAST(CREATEDBY AS INT) AS CREATEDBY,
    TRY_CAST(MODIFIEDBY AS INT) AS MODIFIEDBY,

    -- Extra
    TRIM(USERRESTRICTIONS) AS USERRESTRICTIONS,

    -- Audit
    _FIVETRAN_DELETED AS _FIVETRAN_DELETED,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE

from source_data

)

select * from cleaned
