{% set company = var('company', 'Unknown company') | lower %}
{% set sourcesystem = var('sourcesystem', 'Unknown source') | lower %}

{{ config(
    database = get_target_database(company),
    materialized = 'incremental',
    incremental_strategy = 'merge',
    unique_key = 'PROJECT_ID'
) }}

with source_data as (

    select *
    from {{ get_raw_source(company, sourcesystem, 'PROJECT') }}
    
    {% if is_incremental() %}
        where WHENMODIFIED > (
            select coalesce(max(WHEN_MODIFIED), '1900-01-01'::timestamp_ntz)
            from {{ this }}
        )
        or _FIVETRAN_DELETED = true
    {% endif %}

),

cleaned as (

    select
        -- Primary Key
        UPPER(TRIM(PROJECTID)) AS PROJECT_ID,

        -- Core Identifiers
        TRY_CAST(RECORDNO AS INT) AS RECORD_NO,
        TRIM(RECORD_URL) AS RECORD_URL,
        TRIM(NAME) AS PROJECT_NAME,
        TRIM(DESCRIPTION) AS DESCRIPTION,
        TRIM(STATUS) AS STATUS,
        TRIM(PROJECTSTATUS) AS PROJECT_STATUS,
        TRY_CAST(PROJECTSTATUSKEY AS INT) AS PROJECT_STATUS_KEY,
        TRIM(PROJECTCATEGORY) AS PROJECT_CATEGORY,
        TRIM(PROJECTTYPE) AS PROJECT_TYPE,
        TRY_CAST(PROJECTTYPEKEY AS INT) AS PROJECT_TYPE_KEY,

        -- Dates
        CAST(BEGINDATE AS DATE) AS BEGIN_DATE,
        CAST(PRJ_ESTIMATED_CLOSING_DATE AS DATE) AS ESTIMATED_CLOSING_DATE,
        CAST(PRJ_TARGET_OPENING_DATE AS DATE) AS TARGET_OPENING_DATE,
        CAST(WHENCREATED AS TIMESTAMP_NTZ) AS WHEN_CREATED,
        CAST(WHENMODIFIED AS TIMESTAMP_NTZ) AS WHEN_MODIFIED,

        -- Financials
        TRIM(BILLINGOVERMAX) AS BILLING_OVER_MAX,
        TRIM(BILLINGPRICING) AS BILLING_PRICING,
        TRIM(EXPENSEPRICING) AS EXPENSE_PRICING,
        EXPENSERATE AS EXPENSE_RATE,             -- numeric
        TRIM(POAPPRICING) AS PO_APP_PRICING,
        POAPRATE AS PO_APP_RATE,                 -- numeric
        OBSPERCENTCOMPLETE AS OBS_PERCENT_COMPLETE, -- numeric
        TRIM(CURRENCY) AS CURRENCY,

        -- Flags
        CAST(BILLABLEAPPODEFAULT AS BOOLEAN) AS BILLABLE_APPO_DEFAULT,
        CAST(BILLABLEEXPDEFAULT AS BOOLEAN) AS BILLABLE_EXP_DEFAULT,
        CAST(EXCLUDEEXPENSES AS BOOLEAN) AS EXCLUDE_EXPENSES,
        CAST(INVOICEWITHPARENT AS BOOLEAN) AS INVOICE_WITH_PARENT,
        CAST(PREVENTAPPO AS BOOLEAN) AS PREVENT_APPO,
        CAST(PREVENTEXPENSE AS BOOLEAN) AS PREVENT_EXPENSE,
        CAST(PREVENTGENINVOICE AS BOOLEAN) AS PREVENT_GEN_INVOICE,
        CAST(PREVENTTIMESHEET AS BOOLEAN) AS PREVENT_TIMESHEET,
        CAST(WIPEXCLUDE AS BOOLEAN) AS WIPE_EXCLUDE,

        -- Hierarchy
        TRIM(PARENTID) AS PARENT_ID,
        TRY_CAST(PARENTKEY AS INT) AS PARENT_KEY,
        TRIM(PARENTNAME) AS PARENT_NAME,
        TRIM(ROOTPARENTID) AS ROOT_PARENT_ID,
        TRY_CAST(ROOTPARENTKEY AS INT) AS ROOT_PARENT_KEY,
        TRIM(ROOTPARENTNAME) AS ROOT_PARENT_NAME,

        -- Class / Location
        TRIM(CLASSID) AS CLASS_ID,
        TRY_CAST(CLASSKEY AS INT) AS CLASS_KEY,
        TRIM(CLASSNAME) AS CLASS_NAME,
        TRIM(LOCATIONID) AS LOCATION_ID,
        TRIM(LOCATIONNAME) AS LOCATION_NAME,
        TRY_CAST(PROJECTLOCATIONKEY AS INT) AS PROJECT_LOCATION_KEY,

        -- Mega Entity / Location
        TRIM(MEGAENTITYID) AS MEGA_ENTITY_ID,
        TRY_CAST(MEGAENTITYKEY AS INT) AS MEGA_ENTITY_KEY,
        TRIM(MEGAENTITYNAME) AS MEGA_ENTITY_NAME,
        TRIM(MELOCATIONID) AS ME_LOCATION_ID,
        TRY_CAST(MELOCATIONKEY AS INT) AS ME_LOCATION_KEY,
        TRIM(MELOCATIONNAME) AS ME_LOCATION_NAME,

        -- Relationships
        TRY_CAST(CREATEDBY AS INT) AS CREATED_BY,
        TRY_CAST(MODIFIEDBY AS INT) AS MODIFIED_BY,

        -- Extra
        TRIM(USERRESTRICTIONS) AS USER_RESTRICTIONS,

        -- Audit
        _FIVETRAN_DELETED AS IS_DELETED,
        CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE

    from source_data
)

select * from cleaned
