{% set company = var('company', 'Unknown company') | lower %}
{% set sourcesystem  = var('sourcesystem', 'Unknown source') | lower %}
{{ config(enabled = var('sourcesystem', 'none') == 'sage') }}

{{ config(
    database = get_target_database(company),
    materialized = 'incremental',
    incremental_strategy = 'merge',
    unique_key = 'ID'
) }}

with source_data as (
    select *
    from {{ get_raw_source(company, sourcesystem, 'ASSET') }}
    {% if is_incremental() %}
    where TRY_CAST(UPDATED_AT AS TIMESTAMP_NTZ) > (
        select coalesce(max(UPDATED_AT), '1900-01-01'::timestamp_ntz)
        from {{ this }}
    )
    or _FIVETRAN_DELETED = true
    {% endif %}
),

cleaned as (
    SELECT
    -- Primary Key
    TRY_CAST(ID AS INT) AS ID,

    -- Core Identifiers & Descriptors
    TRIM(ASSET_NAME) AS ASSET_NAME,
    TRIM(NAME) AS NAME,
    TRIM(DESCRIPTION) AS DESCRIPTION,
    TRIM(ASSET_TAG) AS ASSET_TAG,
    TRIM(SERIAL_NUMBER) AS SERIAL_NUMBER,
    TRIM(OWNING_ENTITY) AS OWNING_ENTITY,
    TRIM(RECORD_URL) AS RECORD_URL,
    TRIM(VALIDATION_STATUS) AS VALIDATION_STATUS,

    -- Financials
    TRY_CAST(ASSET_COST AS FLOAT) AS ASSET_COST,
    TRY_CAST(ACCUMULATED_DEPRECIATION_BEFORE AS FLOAT) AS ACCUMULATED_DEPRECIATION_BEFORE,
    TRY_CAST(ACCUMULATED_DEPRECIATION_REPORTS AS FLOAT) AS ACCUMULATED_DEPRECIATION_REPORTS,
    CAST(TAX_DEPRECIATION_GENERATED_COST_CHANGED AS BOOLEAN) AS TAX_DEPRECIATION_GENERATED_COST_CHANGED,

    -- Dates
    COALESCE(TRY_TO_DATE(ASSET_GL_POSTING_DATE, 'MM/DD/YYYY'), TRY_TO_DATE(ASSET_GL_POSTING_DATE, 'MM-DD-YY')) AS ASSET_GL_POSTING_DATE,
    COALESCE(TRY_TO_DATE(DATE_PLACED_IN_SERVI, 'MM/DD/YYYY'), TRY_TO_DATE(DATE_PLACED_IN_SERVI, 'MM-DD-YY')) AS DATE_PLACED_IN_SERVI,
    COALESCE(TRY_TO_DATE(LAST_POSTING_DATE_BEFORE_IMPORT, 'MM/DD/YYYY'), TRY_TO_DATE(LAST_POSTING_DATE_BEFORE_IMPORT, 'MM-DD-YY')) AS LAST_POSTING_DATE_BEFORE_IMPORT,
    TRY_CAST(CREATED_AT AS TIMESTAMP_NTZ) AS CREATED_AT,
    TRY_CAST(UPDATED_AT AS TIMESTAMP_NTZ) AS UPDATED_AT,

    -- Relationships
    TRY_CAST(ATTACH_VENDOR AS INT) AS ATTACH_VENDOR,
    TRY_CAST(CREATED_BY AS INT) AS CREATED_BY,
    TRY_CAST(UPDATED_BY AS INT) AS UPDATED_BY,
    TRY_CAST(PROCESS AS INT) AS PROCESS,
    TRY_CAST(RASSET_CLASS AS INT) AS RASSET_CLASS,
    TRY_CAST(RCLASS AS INT) AS RCLASS,
    TRY_CAST(RCURRENCY AS INT) AS RCURRENCY,
    TRY_CAST(RDEPARTMENT AS INT) AS RDEPARTMENT,
    TRY_CAST(RLOCATION AS INT) AS RLOCATION,
    TRY_CAST(RPROJECT AS INT) AS RPROJECT,
    TRY_CAST(RREVENUE_CENTER AS INT) AS RREVENUE_CENTER,
    TRY_CAST(RVENDOR AS INT) AS RVENDOR,
    TRY_CAST(STATUS AS INT) AS STATUS,

    -- Attachments / Extra Info
    TRIM(ATTACH_CURRENCY_CODE) AS ATTACH_CURRENCY_CODE,
    TRIM(ATTACH_DEPARTMENT) AS ATTACH_DEPARTMENT,
    TRIM(AP_BILL_ITEM_RECORDNO) AS AP_BILL_ITEM_RECORDNO,

    -- Flags & Booleans
    CAST(ASSET_COST_CHANGE_ONLY AS BOOLEAN) AS ASSET_COST_CHANGE_ONLY,
    CAST(CREATE_DEP_ON_IMPORT_FLAG AS BOOLEAN) AS CREATE_DEP_ON_IMPORT_FLAG,
    CAST(FLAG_API_UPDATE AS BOOLEAN) AS FLAG_API_UPDATE,
    CAST(FLAG_ATTACH_CURRENCY_CODE_UPDATE AS BOOLEAN) AS FLAG_ATTACH_CURRENCY_CODE_UPDATE,
    CAST(FLAG_ATTACH_DEPARTMENT_UPDATE AS BOOLEAN) AS FLAG_ATTACH_DEPARTMENT_UPDATE,
    CAST(FLAG_ATTACH_VENDOR_UPDATE AS BOOLEAN) AS FLAG_ATTACH_VENDOR_UPDATE,
    CAST(FLAG_WARRANTY_EXPIRE_DATE_UPDATE AS BOOLEAN) AS FLAG_WARRANTY_EXPIRE_DATE_UPDATE,
    CAST(FLAG_WARRANTY_EXPIRE_EMAIL_SENT_UPDATE AS BOOLEAN) AS FLAG_WARRANTY_EXPIRE_EMAIL_SENT_UPDATE,
    CAST(IS_FOREIGN_CURRENCY AS BOOLEAN) AS IS_FOREIGN_CURRENCY,
    CAST(SEND_WARRANTY_EXPIRE_EMAIL AS BOOLEAN) AS SEND_WARRANTY_EXPIRE_EMAIL,
    CAST(WARRANTY_EXPIRE_EMAIL_SENT AS BOOLEAN) AS WARRANTY_EXPIRE_EMAIL_SENT,

    -- Audit
    _FIVETRAN_DELETED AS _FIVETRAN_DELETED,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE
FROM source_data

)

select *
from cleaned
