{% set company = var('company', 'Unknown company') | lower %}
{% set sourcesystem  = var('sourcesystem', 'Unknown source') | lower %}
{{ config(enabled = var('sourcesystem', 'none') == 'sage') }}

{{ config(
    database = get_target_database(company),
    materialized = 'incremental',
    incremental_strategy = 'merge',
    unique_key = 'BANKACCOUNTID'
) }}

with source_data as (
    select *
    from {{ get_raw_source(company, sourcesystem, 'BANKACCOUNT') }}
    {% if is_incremental() %}
    where CAST(WHENMODIFIED AS TIMESTAMP_NTZ) > (
        select coalesce(max(WHENMODIFIED), '1900-01-01'::timestamp_ntz)
        from {{ this }}
    )
    or _FIVETRAN_DELETED = true
    {% endif %}
),

cleaned as (
    select
        -- Primary Key
        UPPER(TRIM(BANKACCOUNTID)) AS BANKACCOUNTID,

        -- Core Identifiers
        TRY_CAST(BANKACCOUNTNO AS INT) AS BANKACCOUNTNO,
        TRIM(BANKACCOUNTTYPE) AS BANKACCOUNTTYPE,
        TRIM(BANKNAME) AS BANKNAME,
        CASE 
            WHEN UPPER(BANKNAME) LIKE 'UMB%' THEN 'UMB'
            WHEN UPPER(BANKNAME) LIKE 'JP MORGAN%' OR UPPER(BANKNAME) LIKE 'JPMORGAN%' THEN 'JPMorgan Chase Bank'
            WHEN UPPER(BANKNAME) LIKE 'BILL.COM%' THEN 'Bill.com'
            WHEN UPPER(BANKNAME) LIKE 'WELLS FARGO%' THEN 'Wells Fargo'
            WHEN UPPER(BANKNAME) LIKE 'BANK OF OKLAHOMA%' THEN 'Bank of Oklahoma'
            WHEN UPPER(BANKNAME) LIKE 'SANDY SPRING BANK%' THEN 'Sandy Spring Bank'
            WHEN UPPER(BANKNAME) LIKE 'BANCFIRST%' THEN 'BancFirst'
            WHEN UPPER(BANKNAME) LIKE 'FIRST FIDELITY BANK%' THEN 'First Fidelity Bank'
            WHEN UPPER(BANKNAME) LIKE 'SILICON VALLEY BANK%' THEN 'Silicon Valley Bank'
            WHEN UPPER(BANKNAME) LIKE 'ALL AMERICA BANK%' THEN 'All America Bank'
            WHEN UPPER(BANKNAME) LIKE 'INTERBANK%' THEN 'InterBank'
            ELSE TRIM(BANKNAME)
        END AS CLEAN_BANKNAME,
        TRIM(NAMEONTHEACCOUNT) AS NAMEONTHEACCOUNT,
        TRY_CAST(RECORDNO AS INT) AS RECORDNO,
        TRIM(STATUS) AS STATUS,

        -- Contact Info
        TRIM(CHECKINFOCONTACT_COMPANYNAME) AS CHECKINFOCONTACT_COMPANYNAME,
        TRIM(CHECKINFOCONTACT_CONTACTNAME) AS CHECKINFOCONTACT_CONTACTNAME,
        TRIM(CHECKINFOCONTACT_PHONE_1) AS CHECKINFOCONTACT_PHONE_1,
        TRIM(CHECKINFOCONTACT_MAILADDRESS_ADDRESS_1) AS CHECKINFOCONTACT_MAILADDRESS_ADDRESS_1,
        TRIM(CHECKINFOCONTACT_MAILADDRESS_ADDRESS_2) AS CHECKINFOCONTACT_MAILADDRESS_ADDRESS_2,
        TRIM(CHECKINFOCONTACT_MAILADDRESS_CITY) AS CHECKINFOCONTACT_MAILADDRESS_CITY,
        TRIM(CHECKINFOCONTACT_MAILADDRESS_STATE) AS CHECKINFOCONTACT_MAILADDRESS_STATE,
        TRIM(CHECKINFOCONTACT_MAILADDRESS_ZIP) AS CHECKINFOCONTACT_MAILADDRESS_ZIP,
        TRIM(CHECKINFOCONTACT_MAILADDRESS_COUNTRY) AS CHECKINFOCONTACT_MAILADDRESS_COUNTRY,
        TRIM(CHECKINFOCONTACT_MAILADDRESS_COUNTRYCODE) AS CHECKINFOCONTACT_MAILADDRESS_COUNTRYCODE,

        -- General Address
       
        TRIM(MAILADDRESS_ADDRESS_1) AS MAILADDRESS_ADDRESS_1,
        TRIM(MAILADDRESS_ADDRESS_2) AS MAILADDRESS_ADDRESS_2,
        TRIM(MAILADDRESS_CITY) AS MAILADDRESS_CITY,
        TRIM(MAILADDRESS_STATE) AS MAILADDRESS_STATE,
        TRIM(MAILADDRESS_ZIP) AS MAILADDRESS_ZIP,
        TRIM(MAILADDRESS_COUNTRY) AS MAILADDRESS_COUNTRY,
        TRIM(MAILADDRESS_COUNTRYCODE) AS MAILADDRESS_COUNTRYCODE,

        -- Check Layout
        TRIM(CHECKLAYOUT_BANKACCTALIGN) AS CHECKLAYOUT_BANKACCTALIGN,
        TRY_CAST(CHECKLAYOUT_CHECKNOLENGTH AS INT) AS CHECKLAYOUT_CHECKNOLENGTH,
        TRIM(CHECKLAYOUT_CHECKPAPERFORMAT) AS CHECKLAYOUT_CHECKPAPERFORMAT,
        TRIM(CHECKLAYOUT_CHECKPRINTFORMAT) AS CHECKLAYOUT_CHECKPRINTFORMAT,
        CAST(CHECKLAYOUT_DFLTCNYADDR AS BOOLEAN) AS CHECKLAYOUT_DFLTCNYADDR,
        TRIM(CHECKLAYOUT_DISPLAYLOCATIONAS) AS CHECKLAYOUT_DISPLAYLOCATIONAS,
        CAST(CHECKLAYOUT_MICRTRANSCODE AS BOOLEAN) AS CHECKLAYOUT_MICRTRANSCODE,
        CAST(CHECKLAYOUT_ONUS AS BOOLEAN) AS CHECKLAYOUT_ONUS,
        TRIM(CHECKLAYOUT_ONUS_32) AS CHECKLAYOUT_ONUS_32,
        CAST(CHECKLAYOUT_PRINTLINEITEMS AS BOOLEAN) AS CHECKLAYOUT_PRINTLINEITEMS,
        TRIM(CHECKLAYOUT_SIGNATUREIMAGE_1) AS CHECKLAYOUT_SIGNATUREIMAGE_1,
        TRY_CAST(CHECKLAYOUT_SPACESTOAPPEND AS INT) AS CHECKLAYOUT_SPACESTOAPPEND,
        CAST(CHECKLAYOUT_USDTEXT AS BOOLEAN) AS CHECKLAYOUT_USDTEXT,

        -- Financial Data
        TRIM(CURRENCY) AS CURRENCY,
        TRY_CAST(GLACCOUNTNO AS INT) AS GLACCOUNTNO,
        TRY_CAST(INTERESTEARNEDGLACCOUNT AS INT) AS INTERESTEARNEDGLACCOUNT,
        TRY_CAST(SERVICECHARGEGLACCOUNT AS INT) AS SERVICECHARGEGLACCOUNT,
        TRIM(FINANCIALDATA_APJOURNAL) AS FINANCIALDATA_APJOURNAL,
        TRIM(FINANCIALDATA_ARJOURNAL) AS FINANCIALDATA_ARJOURNAL,
        TRIM(FINANCIALDATA_RECONMODE) AS FINANCIALDATA_RECONMODE,
        TRY_CAST(RULESETKEY AS INT) AS RULESETKEY,
        TRY_CAST(NEXTCHECK AS INT) AS NEXTCHECK,
        CAST(FORWFPM AS BOOLEAN) AS FORWFPM,
        CAST(SHARECHECKNO AS BOOLEAN) AS SHARECHECKNO,
        TRY_CAST(LASTRECONCILEDBALANCE AS FLOAT) AS LASTRECONCILEDBALANCE,

        -- Dates
        CAST(CUTOFFDATE AS DATE) AS CUTOFFDATE,
        CAST(LASTRECONCILEDDATE AS DATE) AS LASTRECONCILEDDATE,
        CAST(WPBLASTBANKFEEDDATE AS DATE) AS WPBLASTBANKFEEDDATE,
        CAST(WPBLASTTRANSACTIONSRECEIVED AS DATE) AS WPBLASTTRANSACTIONSRECEIVED,
        CAST(WHENCREATED AS TIMESTAMP_NTZ) AS WHENCREATED,
        CAST(WHENMODIFIED AS TIMESTAMP_NTZ) AS WHENMODIFIED,

        -- Location & Other Info
        TRIM(LOCATIONID) AS LOCATIONID,
        TRIM(PHONE) AS PHONE,
        TRIM(WPBREFRESHSTATUS_2) AS WPBREFRESHSTATUS_2,
        TRIM(WPBSTATUS) AS WPBSTATUS,

        -- Relationships
        TRY_CAST(CREATEDBY AS INT) AS CREATEDBY,
        TRY_CAST(MODIFIEDBY AS INT) AS MODIFIEDBY,

        -- Flags / Deletes
        _FIVETRAN_DELETED AS _FIVETRAN_DELETED,

        -- Audit
        CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE
        FROM source_data

)

select *
from cleaned
