{% set company = var('company', 'Unknown company') | lower %}
{% set sourcesystem = var('sourcesystem', 'Unknown source') | lower %}
{{ config(enabled = var('sourcesystem', 'none') == 'sage') }}

{{ config(
    database = get_target_database(company),
    materialized = 'incremental',
    incremental_strategy = 'merge',
    unique_key = 'CUSTOMER_ID'
) }}

with source_data as (
    select *
    from {{ get_raw_source(company, sourcesystem, 'CUSTOMER') }}
    {% if is_incremental() %}
    where CAST(WHENMODIFIED AS TIMESTAMP_NTZ) > (
        select coalesce(max(WHEN_MODIFIED), '1900-01-01'::timestamp_ntz)
        from {{ this }}
    )
    or _FIVETRAN_DELETED = true
    {% endif %}
),

cleaned as (
    SELECT
    -- Primary Key
    UPPER(TRIM(CUSTOMERID)) AS CUSTOMERID,

    -- Core Identifiers
    TRY_CAST(RECORDNO AS INT) AS RECORDNO,
    TRIM(NAME) AS NAME,
    TRIM(ENTITY) AS ENTITY,
    TRIM(STATUS) AS STATUS,

    -- Accounts / Terms
    TRY_CAST(ACCOUNTKEY AS INT) AS ACCOUNTKEY,
    TRY_CAST(ARACCOUNT AS INT) AS ARACCOUNT,
    TRIM(ARACCOUNTTITLE) AS ARACCOUNTTITLE,
    TRIM(ARINVOICEPRINTTEMPLATEID) AS ARINVOICEPRINTTEMPLATEID,
    TRIM(TERMNAME) AS TERMNAME,
    TRY_CAST(TERMSKEY AS INT) AS TERMSKEY,
    TRIM(TERMVALUE) AS TERMVALUE,

    -- Customer Type
    TRIM(CUSTTYPE) AS CUSTTYPE,
    TRY_CAST(CUSTTYPEKEY AS INT) AS CUSTTYPEKEY,

    -- Contact Info (Display Contact)
    TRIM(DISPLAYCONTACT_COMPANYNAME) AS DISPLAYCONTACT_COMPANYNAME,
    TRIM(DISPLAYCONTACT_CONTACTNAME) AS DISPLAYCONTACT_CONTACTNAME,
    TRIM(DISPLAYCONTACT_FIRSTNAME) AS DISPLAYCONTACT_FIRSTNAME,
    TRIM(DISPLAYCONTACT_LASTNAME) AS DISPLAYCONTACT_LASTNAME,
    TRIM(DISPLAYCONTACT_INITIAL) AS DISPLAYCONTACT_INITIAL,
    TRIM(DISPLAYCONTACT_EMAIL_1) AS DISPLAYCONTACT_EMAIL_1,
    TRIM(DISPLAYCONTACT_EMAIL_2) AS DISPLAYCONTACT_EMAIL_2,
    TRIM(DISPLAYCONTACT_CELLPHONE) AS DISPLAYCONTACT_CELLPHONE,
    TRIM(DISPLAYCONTACT_PHONE_1) AS DISPLAYCONTACT_PHONE_1,
    TRIM(DISPLAYCONTACT_PRINTAS) AS DISPLAYCONTACT_PRINTAS,
    TRIM(DISPLAYCONTACT_STATUS) AS DISPLAYCONTACT_STATUS,
    CAST(DISPLAYCONTACT_TAXABLE AS BOOLEAN) AS DISPLAYCONTACT_TAXABLE,
    CAST(DISPLAYCONTACT_VISIBLE AS BOOLEAN) AS DISPLAYCONTACT_VISIBLE,
    TRY_CAST(DISPLAYCONTACTKEY AS INT) AS DISPLAYCONTACTKEY,

    -- Contact Address
    TRIM(DISPLAYCONTACT_MAILADDRESS_ADDRESS_1) AS DISPLAYCONTACT_MAILADDRESS_ADDRESS_1,
    TRIM(DISPLAYCONTACT_MAILADDRESS_ADDRESS_2) AS DISPLAYCONTACT_MAILADDRESS_ADDRESS_2,
    TRIM(DISPLAYCONTACT_MAILADDRESS_ADDRESS_3) AS DISPLAYCONTACT_MAILADDRESS_ADDRESS_3,
    TRIM(DISPLAYCONTACT_MAILADDRESS_CITY) AS DISPLAYCONTACT_MAILADDRESS_CITY,
    TRIM(DISPLAYCONTACT_MAILADDRESS_STATE) AS DISPLAYCONTACT_MAILADDRESS_STATE,
    TRIM(DISPLAYCONTACT_MAILADDRESS_ZIP) AS DISPLAYCONTACT_MAILADDRESS_ZIP,
    TRIM(DISPLAYCONTACT_MAILADDRESS_COUNTRY) AS DISPLAYCONTACT_MAILADDRESS_COUNTRY,
    TRIM(DISPLAYCONTACT_MAILADDRESS_COUNTRYCODE) AS DISPLAYCONTACT_MAILADDRESS_COUNTRYCODE,

    -- Mega Entity
    TRIM(MEGAENTITYID) AS MEGAENTITYID,
    TRY_CAST(MEGAENTITYKEY AS INT) AS MEGAENTITYKEY,
    TRIM(MEGAENTITYNAME) AS MEGAENTITYNAME,

    -- Territory
    TRIM(TERRITORYID) AS TERRITORYID,
    TRIM(TERRITORYKEY) AS TERRITORYKEY,
    TRIM(TERRITORYNAME) AS TERRITORYNAME,

    -- Financials
    TRY_CAST(TOTALDUE AS FLOAT) AS TOTALDUE,
    TRIM(PRCLST_OVERRIDE) AS PRCLST_OVERRIDE,
    TRIM(DELIVERY_OPTIONS) AS DELIVERY_OPTIONS,

    -- Flags
    CAST(EMAILOPTIN AS BOOLEAN) AS EMAILOPTIN,
    CAST(ENABLEONLINEACHPAYMENT AS BOOLEAN) AS ENABLEONLINEACHPAYMENT,
    CAST(ENABLEONLINECARDPAYMENT AS BOOLEAN) AS ENABLEONLINECARDPAYMENT,
    CAST(ONETIME AS BOOLEAN) AS ONETIME,
    CAST(ONHOLD AS BOOLEAN) AS ONHOLD,

    -- Dates
    CAST(LAST_INVOICEDATE AS DATE) AS LAST_INVOICEDATE,
    CAST(LAST_STATEMENTDATE AS DATE) AS LAST_STATEMENTDATE,
    CAST(WHENCREATED AS TIMESTAMP_NTZ) AS WHENCREATED,
    CAST(WHENMODIFIED AS TIMESTAMP_NTZ) AS WHENMODIFIED,

    -- Relationships
    TRY_CAST(CREATEDBY AS INT) AS CREATEDBY,
    TRIM(CREATEDBYLOGINID) AS CREATEDBYLOGINID,
    TRY_CAST(MODIFIEDBY AS INT) AS MODIFIEDBY,
    TRIM(MODIFIEDBYLOGINID) AS MODIFIEDBYLOGINID,

    -- Extra
    TRIM(OBJECTRESTRICTION) AS OBJECTRESTRICTION,

    -- Flags / Deletes
    _FIVETRAN_DELETED AS _FIVETRAN_DELETED,

    -- Audit
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE
FROM source_data

)

select *
from cleaned
