{% set company = var('company', 'Unknown company') | lower %}
{% set sourcesystem  = var('sourcesystem', 'Unknown source') | lower %}

{{ config(
    database = get_target_database(company),
    materialized = 'incremental',
    incremental_strategy = 'merge',
    unique_key = 'BANK_ACCOUNT_ID'
) }}

with source_data as (
    select *
    from {{ get_raw_source(company, sourcesystem, 'BANKACCOUNT') }}
    {% if is_incremental() %}
    where CAST(WHENMODIFIED AS TIMESTAMP_NTZ) > (
        select coalesce(max(WHEN_MODIFIED), '1900-01-01'::timestamp_ntz)
        from {{ this }}
    )
    or _FIVETRAN_DELETED = true
    {% endif %}
),

cleaned as (
    select
        -- Primary Key
        UPPER(TRIM(BANKACCOUNTID)) AS BANK_ACCOUNT_ID,

        -- Core Identifiers
        TRY_CAST(BANKACCOUNTNO AS INT) AS BANK_ACCOUNT_NO,
        TRIM(BANKACCOUNTTYPE) AS BANK_ACCOUNT_TYPE,
        TRIM(BANKNAME) AS BANK_NAME,
        CASE 
            WHEN UPPER(BANKNAME) LIKE 'UMB%' THEN 'UMB'
            WHEN UPPER(BANKNAME) LIKE 'JP MORGAN%' OR UPPER(BANKNAME) LIKE 'JPMORGAN%' THEN 'JPMorgan Chase Bank'
            WHEN UPPER(BANKNAME) LIKE 'BILL.COM%' THEN 'Bill.com'
            WHEN UPPER(BANKNAME) LIKE 'WELLS FARGO%' THEN 'Wells Fargo'
            WHEN UPPER(BANKNAME) LIKE 'BANK OF OKLAHOMA%' THEN 'Bank of Oklahoma'
            WHEN UPPER(BANKNAME) LIKE 'SANDY SPRING BANK%' THEN 'Sandy Spring Bank'
            WHEN UPPER(BANKNAME) LIKE 'BANCFIRST%' THEN 'BancFirst'
            WHEN UPPER(BANKNAME) LIKE 'FIRST FIDELITY BANK%' THEN 'First Fidelity Bank'
            WHEN UPPER(BANKNAME) LIKE 'SILICON VALLEY BANK%' THEN 'Silicon Valley Bank'
            WHEN UPPER(BANKNAME) LIKE 'ALL AMERICA BANK%' THEN 'All America Bank'
            WHEN UPPER(BANKNAME) LIKE 'INTERBANK%' THEN 'InterBank'
            ELSE TRIM(BANKNAME)
        END AS CLEAN_BANK_NAME,
        TRIM(NAMEONTHEACCOUNT) AS NAME_ON_THE_ACCOUNT,
        TRY_CAST(RECORDNO AS INT) AS RECORD_NO,
        TRIM(STATUS) AS STATUS,

        -- Contact Info
        TRIM(CHECKINFOCONTACT_COMPANYNAME) AS CHECKINFO_COMPANY_NAME,
        TRIM(CHECKINFOCONTACT_CONTACTNAME) AS CHECKINFO_CONTACT_NAME,
        TRIM(CHECKINFOCONTACT_PHONE_1) AS CHECKINFO_PHONE,
        TRIM(CHECKINFOCONTACT_MAILADDRESS_ADDRESS_1) AS CHECKINFO_ADDR_LINE_1,
        TRIM(CHECKINFOCONTACT_MAILADDRESS_ADDRESS_2) AS CHECKINFO_ADDR_LINE_2,
        TRIM(CHECKINFOCONTACT_MAILADDRESS_CITY) AS CHECKINFO_CITY,
        TRIM(CHECKINFOCONTACT_MAILADDRESS_STATE) AS CHECKINFO_STATE,
        TRIM(CHECKINFOCONTACT_MAILADDRESS_ZIP) AS CHECKINFO_ZIP,
        TRIM(CHECKINFOCONTACT_MAILADDRESS_COUNTRY) AS CHECKINFO_COUNTRY,
        TRIM(CHECKINFOCONTACT_MAILADDRESS_COUNTRYCODE) AS CHECKINFO_COUNTRY_CODE,

        -- General Address
        TRIM(MAILADDRESS_ADDRESS_1) AS MAIL_ADDR_LINE_1,
        TRIM(MAILADDRESS_ADDRESS_2) AS MAIL_ADDR_LINE_2,
        TRIM(MAILADDRESS_CITY) AS MAIL_CITY,
        TRIM(MAILADDRESS_STATE) AS MAIL_STATE,
        TRIM(MAILADDRESS_ZIP) AS MAIL_ZIP,
        TRIM(MAILADDRESS_COUNTRY) AS MAIL_COUNTRY,
        TRIM(MAILADDRESS_COUNTRYCODE) AS MAIL_COUNTRY_CODE,

        -- Check Layout
        TRIM(CHECKLAYOUT_BANKACCTALIGN) AS CHECKLAYOUT_BANK_ACCT_ALIGN,
        TRY_CAST(CHECKLAYOUT_CHECKNOLENGTH AS INT) AS CHECKLAYOUT_CHECK_NO_LENGTH,
        TRIM(CHECKLAYOUT_CHECKPAPERFORMAT) AS CHECKLAYOUT_CHECK_PAPER_FORMAT,
        TRIM(CHECKLAYOUT_CHECKPRINTFORMAT) AS CHECKLAYOUT_CHECK_PRINT_FORMAT,
        CAST(CHECKLAYOUT_DFLTCNYADDR AS BOOLEAN) AS CHECKLAYOUT_DFLT_CNY_ADDR,
        TRIM(CHECKLAYOUT_DISPLAYLOCATIONAS) AS CHECKLAYOUT_DISPLAY_LOCATION_AS,
        CAST(CHECKLAYOUT_MICRTRANSCODE AS BOOLEAN) AS CHECKLAYOUT_MICR_TRANS_CODE,
        CAST(CHECKLAYOUT_ONUS AS BOOLEAN) AS CHECKLAYOUT_ONUS,
        TRIM(CHECKLAYOUT_ONUS_32) AS CHECKLAYOUT_ONUS_32,
        CAST(CHECKLAYOUT_PRINTLINEITEMS AS BOOLEAN) AS CHECKLAYOUT_PRINT_LINE_ITEMS,
        TRIM(CHECKLAYOUT_SIGNATUREIMAGE_1) AS CHECKLAYOUT_SIGNATURE_IMAGE_1,
        TRY_CAST(CHECKLAYOUT_SPACESTOAPPEND AS INT) AS CHECKLAYOUT_SPACES_TO_APPEND,
        CAST(CHECKLAYOUT_USDTEXT AS BOOLEAN) AS CHECKLAYOUT_USD_TEXT,

        -- Financial Data
        TRIM(CURRENCY) AS CURRENCY,
        TRY_CAST(GLACCOUNTNO AS INT) AS GL_ACCOUNT_NO,
        TRY_CAST(INTERESTEARNEDGLACCOUNT AS INT) AS INTEREST_EARNED_GL_ACCOUNT,
        TRY_CAST(SERVICECHARGEGLACCOUNT AS INT) AS SERVICE_CHARGE_GL_ACCOUNT,
        TRIM(FINANCIALDATA_APJOURNAL) AS FINANCIALDATA_AP_JOURNAL,
        TRIM(FINANCIALDATA_ARJOURNAL) AS FINANCIALDATA_AR_JOURNAL,
        TRIM(FINANCIALDATA_RECONMODE) AS FINANCIALDATA_RECON_MODE,
        TRY_CAST(RULESETKEY AS INT) AS RULESET_KEY,
        TRY_CAST(NEXTCHECK AS INT) AS NEXT_CHECK_NO,
        CAST(FORWFPM AS BOOLEAN) AS FORW_FPM,
        CAST(SHARECHECKNO AS BOOLEAN) AS SHARE_CHECK_NO,
        TRY_CAST(LASTRECONCILEDBALANCE AS FLOAT) AS LAST_RECONCILED_BALANCE,

        -- Dates
        CAST(CUTOFFDATE AS DATE) AS CUTOFF_DATE,
        CAST(LASTRECONCILEDDATE AS DATE) AS LAST_RECONCILED_DATE,
        CAST(WPBLASTBANKFEEDDATE AS DATE) AS WPB_LAST_BANK_FEED_DATE,
        CAST(WPBLASTTRANSACTIONSRECEIVED AS DATE) AS WPB_LAST_TRANSACTIONS_RECEIVED,
        CAST(WHENCREATED AS TIMESTAMP_NTZ) AS WHEN_CREATED,
        CAST(WHENMODIFIED AS TIMESTAMP_NTZ) AS WHEN_MODIFIED,

        -- Location & Other Info
        TRIM(LOCATIONID) AS LOCATION_ID,
        TRIM(PHONE) AS PHONE,
        TRIM(WPBREFRESHSTATUS_2) AS WPB_REFRESH_STATUS,
        TRIM(WPBSTATUS) AS WPB_STATUS,

        -- Relationships
        TRY_CAST(CREATEDBY AS INT) AS CREATED_BY,
        TRY_CAST(MODIFIEDBY AS INT) AS MODIFIED_BY,

        -- Flags / Deletes
        _FIVETRAN_DELETED AS IS_DELETED,

        -- Audit
        CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE
    from source_data
)

select *
from cleaned
