{% set company = var('company', 'unknown_company') | lower %}
{% set sourcesystem = var('sourcesystem', 'unknown_source') | lower %}
{{ config(enabled = var('sourcesystem', 'none') == 'sage') }}

{{ config(
    database = get_target_database(company),
    materialized = 'incremental',
    incremental_strategy = 'merge',
    unique_key = 'RECORDNO'
) }}

with source_data as (
    select *
    from {{ get_raw_source(company, sourcesystem, 'GL_DETAIL') }}
    {% if is_incremental() %}
    where cast(WHENMODIFIED as timestamp_ntz) > (
        select coalesce(max(WHENMODIFIED), '1900-01-01'::timestamp_ntz)
        from {{ this }}
    )
    or _FIVETRAN_DELETED = true
    {% endif %}
),

cleaned as (
    select
        TRIM(RECORDNO) AS RECORDNO,
        TRIM(ACCOUNTNO) AS ACCOUNTNO,
        TRIM(ACCOUNTTITLE) AS ACCOUNTTITLE,
        TRIM(DESCRIPTION) AS DESCRIPTION,
        TRIM(DOCNUMBER) AS DOCNUMBER,
        TRIM(DOCUMENT) AS DOCUMENT,
        CAST(ENTRY_DATE AS DATE) AS ENTRY_DATE,
        TRIM(ENTRY_STATE) AS ENTRY_STATE,
        TRIM(ENTRYDESCRIPTION) AS ENTRYDESCRIPTION,
        TRIM(FINANCIALENTITY) AS FINANCIALENTITY,
        TRIM(RECORDTYPE) AS RECORDTYPE,
        TRIM(REFERENCENO) AS REFERENCENO,
        TRIM(STATE) AS STATE,
        AMOUNT,
        DEBITAMOUNT,
        CREDITAMOUNT,
        TOTALDUE,
        TOTALENTERED,
        TOTALPAID,
        TRX_AMOUNT,
        TRX_DEBITAMOUNT,
        TRX_CREDITAMOUNT,
        TRY_CAST(CLASSDIMKEY AS INT) AS CLASSDIMKEY,
        TRIM(CLASSID) AS CLASSID,
        TRIM(CLASSNAME) AS CLASSNAME,
        TRY_CAST(CUSTENTITY AS INT) AS CUSTENTITY,
        TRY_CAST(CUSTOMERDIMKEY AS INT) AS CUSTOMERDIMKEY,
        TRIM(CUSTOMERID) AS CUSTOMERID,
        TRIM(CUSTOMERNAME) AS CUSTOMERNAME,
        TRY_CAST(PROJECTDIMKEY AS INT) AS PROJECTDIMKEY,
        TRIM(PROJECTID) AS PROJECTID,
        TRIM(PROJECTNAME) AS PROJECTNAME,
        TRY_CAST(VENDENTITY AS INT) AS VENDENTITY,
        TRY_CAST(VENDORDIMKEY AS INT) AS VENDORDIMKEY,
        TRY_CAST(VENDORID AS INT) AS VENDORID,
        TRIM(VENDORNAME) AS VENDORNAME,
        TRY_CAST(ITEMDIMKEY AS INT) AS ITEMDIMKEY,
        TRIM(ITEMID) AS ITEMID,
        TRIM(ITEMNAME) AS ITEMNAME,
        TRY_CAST(GLDIMREVENUE_CENTER AS INT) AS GLDIMREVENUE_CENTER,
        TRIM(DEPARTMENTID) AS DEPARTMENTID,
        TRIM(DEPARTMENTTITLE) AS DEPARTMENTTITLE,
        TRY_CAST(WAREHOUSEDIMKEY AS INT) AS WAREHOUSEDIMKEY,
        TRIM(WAREHOUSEID) AS WAREHOUSEID,
        TRIM(WAREHOUSENAME) AS WAREHOUSENAME,
        CAST(BATCH_DATE AS DATE) AS BATCH_DATE,
        TRY_CAST(BATCH_NO AS INT) AS BATCH_NO,
        TRIM(BATCH_STATE) AS BATCH_STATE,
        TRIM(BATCH_TITLE) AS BATCH_TITLE,
        TRIM(BATCHKEY) AS BATCHKEY,
        TRIM(BOOKID) AS BOOKID,
        TRIM(MODULEKEY) AS MODULEKEY,
        TRY_CAST(OWNERSHIPKEY AS INT) AS OWNERSHIPKEY,
        TRIM(BASECURR) AS BASECURR,
        TRIM(CURRENCY) AS CURRENCY,
        TRIM(SYMBOL) AS SYMBOL,
        CAST(ADJ AS BOOLEAN) AS ADJ,
        TRIM(CLEARED) AS CLEARED,
        CAST(PRCLEARED AS BOOLEAN) AS PRCLEARED,
        CAST(STATISTICAL AS BOOLEAN) AS STATISTICAL,
        CAST(CLRDATE AS DATE) AS CLRDATE,
        CAST(PRCLRDATE AS DATE) AS PRCLRDATE,
        TRIM(PRDESCRIPTION) AS PRDESCRIPTION,
        CAST(WHENCREATED AS DATE) AS WHENCREATED,
        CAST(WHENDUE AS DATE) AS WHENDUE,
        CAST(WHENMODIFIED AS TIMESTAMP_NTZ) AS WHENMODIFIED,
        CAST(WHENPAID AS DATE) AS WHENPAID,
        TRY_CAST(AUCREATEDBY AS INT) AS AUCREATEDBY,
        CAST(AUWHENCREATED AS TIMESTAMP_TZ) AS AUWHENCREATED,
        TRIM(CREATEDBY) AS CREATEDBY,
        TRY_CAST(MODIFIEDBY AS INT) AS MODIFIEDBY,
        CAST(MODIFIED AS TIMESTAMP_TZ) AS MODIFIED,
        TRY_CAST(GLENTRYKEY AS INT) AS GLENTRYKEY,
        TRY_CAST(LINE_NO AS INT) AS LINE_NO,
        TRY_CAST(RDEPRECIATION_SUMMARY AS INT) AS RDEPRECIATION_SUMMARY,
        TRY_CAST(TR_TYPE AS INT) AS TR_TYPE,
        CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE
    from source_data
)

select *
from cleaned
