{% set company = var('company', 'Unknown company') | lower %}
{% set sourcesystem = var('sourcesystem', 'Unknown source') | lower %}
{{ config(enabled = var('sourcesystem', 'none') == 'sage') }}

{{ config(
    database = get_target_database(company),
    materialized = 'incremental',
    incremental_strategy = 'merge',
    unique_key = 'RECORDNO'
) }}

with source_data as (

    select *
    from {{ get_raw_source(company, sourcesystem, 'GL_ENTRY') }}

    {% if is_incremental() %}
        where WHENMODIFIED > (
            select coalesce(max(WHENMODIFIED), '1900-01-01'::timestamp_ntz)
            from {{ this }}
        )
    {% endif %}

),

cleaned as (

    SELECT
    -- Primary Key
    TRY_CAST(RECORDNO AS INT) AS RECORDNO,

    -- Foreign Keys & Identifiers
    TRY_CAST(ACCOUNTKEY AS INT) AS ACCOUNTKEY,
    TRIM(ACCOUNTNO) AS ACCOUNTNO,
    TRIM(ACCOUNTTITLE) AS ACCOUNTTITLE,
    TRY_CAST(BATCH_NUMBER AS INT) AS BATCH_NUMBER,
    TRIM(BATCHNO) AS BATCHNO,
    TRIM(BATCHTITLE) AS BATCHTITLE,
    TRY_CAST(CLASSDIMKEY AS INT) AS CLASSDIMKEY,
    TRIM(CLASSID) AS CLASSID,
    TRIM(CLASSNAME) AS CLASSNAME,
    TRY_CAST(DEPARTMENTKEY AS INT) AS DEPARTMENTKEY,
    TRIM(DEPARTMENT) AS DEPARTMENT,
    TRIM(DEPARTMENTTITLE) AS DEPARTMENTTITLE,
    TRY_CAST(ITEMDIMKEY AS INT) AS ITEMDIMKEY,
    TRIM(ITEMID) AS ITEMID,
    TRIM(ITEMNAME) AS ITEMNAME,
    TRY_CAST(PROJECTDIMKEY AS INT) AS PROJECTDIMKEY,
    TRIM(PROJECTID) AS PROJECTID,
    TRIM(PROJECTNAME) AS PROJECTNAME,
    TRIM(LOCATION) AS LOCATION,
    TRY_CAST(LOCATIONKEY AS INT) AS LOCATIONKEY,
    TRIM(LOCATIONNAME) AS LOCATIONNAME,
    TRY_CAST(VENDORDIMKEY AS INT) AS VENDORDIMKEY,
    TRY_CAST(VENDORID AS INT) AS VENDORID,
    TRIM(VENDORNAME) AS VENDORNAME,
    TRY_CAST(WAREHOUSEDIMKEY AS INT) AS WAREHOUSEDIMKEY,
    TRIM(WAREHOUSEID) AS WAREHOUSEID,
    TRIM(WAREHOUSENAME) AS WAREHOUSENAME,

    -- Core Attributes
    TRIM(DESCRIPTION) AS DESCRIPTION,
    TRIM(DOCUMENT) AS DOCUMENT,
    TRIM(STATE) AS STATE,
    ADJ AS ADJ,
    BILLABLE AS BILLABLE,
    STATISTICAL AS STATISTICAL,
    TRY_CAST(LINE_NO AS INT) AS LINE_NO,
    TRY_CAST(TR_TYPE AS INT) AS TR_TYPE,

    -- Amounts, Currency & Exchange
    AMOUNT,
    TRX_AMOUNT, 
    TRIM(CURRENCY) AS CURRENCY,
    TRIM(BASECURR) AS BASECURR,
    TRY_CAST(EXCHANGE_RATE AS INT) AS EXCHANGE_RATE,
    TRY_CAST(EXCH_RATE_TYPE_ID AS INT) AS EXCH_RATE_TYPE_ID,
    CAST(EXCH_RATE_DATE AS DATE) AS EXCH_RATE_DATE,
    TRY_CAST(GLDIMREVENUE_CENTER AS INT) AS GLDIMREVENUE_CENTER,

    -- Dates
    CAST(BATCH_DATE AS DATE) AS BATCH_DATE,
    CAST(ENTRY_DATE AS DATE) AS ENTRY_DATE,
    CAST(CLRDATE AS DATE) AS CLRDATE,
    CAST(WHENCREATED AS TIMESTAMP_NTZ) AS WHENCREATED,
    CAST(WHENMODIFIED AS TIMESTAMP_NTZ) AS WHENMODIFIED,

    -- Audit
    TRY_CAST(CREATEDBY AS INT) AS CREATEDBY,
    TRIM(CREATEDBYLOGINID) AS CREATEDBYLOGINID,
    TRY_CAST(MODIFIEDBY AS INT) AS MODIFIEDBY,
    TRIM(MODIFIEDBYLOGINID) AS MODIFIEDBYLOGINID,
    TRY_CAST(USERNO AS INT) AS USERNO,

    -- Metadata
    TRIM(RECORD_URL) AS RECORD_URL,
    TRY_CAST(RDEPRECIATION_SUMMARY AS INT) AS RDEPRECIATION_SUMMARY,

    -- Silver Load Metadata
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE

FROM source_data

)

select *
from cleaned
