{% set company = var('company', 'Unknown company') | lower %}
{% set sourcesystem = var('sourcesystem', 'Unknown source') | lower %}
{{ config(enabled = var('sourcesystem', 'none') == 'sage') }}

{{ config(
    database = get_target_database(company),
    materialized = 'incremental',
    incremental_strategy = 'merge',
    unique_key = 'ITEMID'
) }}

with source_data as (

    select *
    from {{ get_raw_source(company, sourcesystem, 'ITEM') }}

    {% if is_incremental() %}
        where WHENMODIFIED > (
            select coalesce(max(WHENMODIFIED), '1900-01-01'::timestamp_ntz)
            from {{ this }}
        )
    {% endif %}

),

cleaned as (

    SELECT
    -- Primary Key
    TRIM(ITEMID) AS ITEMID,

    -- Core Identifiers
    TRY_CAST(RECORDNO AS INT) AS RECORDNO,
    TRIM(NAME) AS NAME,
    TRIM(ITEMTYPE) AS ITEMTYPE,
    TRIM(PRODUCTTYPE) AS PRODUCTTYPE,
    TRIM(PRODUCTLINEID) AS PRODUCTLINEID,
    TRY_CAST(PRODUCTLINERECORDNO AS INT) AS PRODUCTLINERECORDNO,
    TRIM(STATUS) AS STATUS,

    -- Flags
    CAST(ALLOW_BACKORDER AS BOOLEAN) AS ALLOW_BACKORDER,
    CAST(ALLOWMULTIPLETAXGRPS AS BOOLEAN) AS ALLOWMULTIPLETAXGRPS,
    CAST(AUTOPRINTLABEL AS BOOLEAN) AS AUTOPRINTLABEL,
    CAST(BUYTOORDER AS BOOLEAN) AS BUYTOORDER,
    CAST(CNDEFAULTBUNDLE AS BOOLEAN) AS CNDEFAULTBUNDLE,
    CAST(COMPLIANTITEM AS BOOLEAN) AS COMPLIANTITEM,
    CAST(COMPUTEFORSHORTTERM AS BOOLEAN) AS COMPUTEFORSHORTTERM,
    CAST(CONTRACTENABLED AS BOOLEAN) AS CONTRACTENABLED,
    CAST(DROPSHIP AS BOOLEAN) AS DROPSHIP,
    CAST(ENABLE_REPLENISHMENT AS BOOLEAN) AS ENABLE_REPLENISHMENT,
    CAST(ENABLEFULFILLMENT AS BOOLEAN) AS ENABLEFULFILLMENT,
    CAST(ENABLELANDEDCOST AS BOOLEAN) AS ENABLELANDEDCOST,
    CAST(ENGINEERINGAPPROVAL AS BOOLEAN) AS ENGINEERINGAPPROVAL,
    CAST(GIFTCARD AS BOOLEAN) AS GIFTCARD,
    CAST(HASSTARTENDDATES AS BOOLEAN) AS HASSTARTENDDATES,
    CAST(ISSUPPLYITEM AS BOOLEAN) AS ISSUPPLYITEM,
    CAST(MRR AS BOOLEAN) AS MRR,
    CAST(QUALITYCONTROLAPPROVAL AS BOOLEAN) AS QUALITYCONTROLAPPROVAL,
    CAST(RESTRICTEDITEM AS BOOLEAN) AS RESTRICTEDITEM,
    CAST(SAFETYITEM AS BOOLEAN) AS SAFETYITEM,
    CAST(SALESAPPROVAL AS BOOLEAN) AS SALESAPPROVAL,
    CAST(TAXABLE AS BOOLEAN) AS TAXABLE,
    CAST(WEBENABLED AS BOOLEAN) AS WEBENABLED,

    -- Financials / Pricing
    BASEPRICE AS BASEPRICE,
    TRIM(BASEUOM) AS BASEUOM,
    TRIM(COST_METHOD) AS COST_METHOD,
    TRIM(GLGROUP) AS GLGROUP,
    TRY_CAST(GLGRPKEY AS INT) AS GLGRPKEY,
    STANDARD_COST AS STANDARD_COST,
    IONHAND AS IONHAND,
    TRY_CAST(IONORDER AS INT) AS IONORDER,
    IUNCOMMITTED AS IUNCOMMITTED,
    TRY_CAST(MAX_ORDER_QTY AS INT) AS MAX_ORDER_QTY,
    TRY_CAST(REORDER_POINT AS INT) AS REORDER_POINT,
    TRY_CAST(REORDER_QTY AS INT) AS REORDER_QTY,
    TRY_CAST(SAFETY_STOCK AS INT) AS SAFETY_STOCK,
    TRIM(REPLENISHMENT_METHOD) AS REPLENISHMENT_METHOD,
    TRIM(DEFAULT_CONVERSIONTYPE) AS DEFAULT_CONVERSIONTYPE,
    TRIM(DEFAULT_REPLENISHMENT_UOM) AS DEFAULT_REPLENISHMENT_UOM,

    -- Rev Rec & Contract
    TRY_CAST(DEFAULTREVRECTEMPLKEY AS INT) AS DEFAULTREVRECTEMPLKEY,
    TRIM(DEFCONTRACTDEFERRALSTATUS) AS DEFCONTRACTDEFERRALSTATUS,
    TRIM(DEFCONTRACTDELIVERYSTATUS) AS DEFCONTRACTDELIVERYSTATUS,
    TRY_CAST(DEFERREDREVACCTKEY AS INT) AS DEFERREDREVACCTKEY,
    TRIM(REVPRINTING) AS REVPRINTING,
    TRIM(VSOECATEGORY) AS VSOECATEGORY,
    TRIM(VSOEDLVRSTATUS) AS VSOEDLVRSTATUS,
    TRIM(VSOEREVDEFSTATUS) AS VSOEREVDEFSTATUS,

    -- Units of Measure
    TRIM(UOM_INVUOMDETAIL_UNIT) AS UOM_INVUOMDETAIL_UNIT,
    TRY_CAST(UOM_POUOMDETAIL_CONVFACTOR AS INT) AS UOM_POUOMDETAIL_CONVFACTOR,
    TRIM(UOM_POUOMDETAIL_UNIT) AS UOM_POUOMDETAIL_UNIT,
    TRY_CAST(UOM_SOUOMDETAIL_CONVFACTOR AS INT) AS UOM_SOUOMDETAIL_CONVFACTOR,
    TRIM(UOM_SOUOMDETAIL_UNIT) AS UOM_SOUOMDETAIL_UNIT,
    TRIM(UOMGRP) AS UOMGRP,
    TRY_CAST(UOMGRPKEY AS INT) AS UOMGRPKEY,

    -- Extra
    TRIM(EXTENDED_DESCRIPTION) AS EXTENDED_DESCRIPTION,
    TRIM(NOTE) AS NOTE,

    -- Relationships
    TRY_CAST(CREATEDBY AS INT) AS CREATEDBY,
    TRY_CAST(MODIFIEDBY AS INT) AS MODIFIEDBY,

    -- Dates
    CAST(WHENCREATED AS TIMESTAMP_NTZ) AS WHENCREATED,
    CAST(WHENMODIFIED AS TIMESTAMP_NTZ) AS WHENMODIFIED,
    CAST(WHENLASTSOLD AS DATE) AS WHENLASTSOLD,
    CAST(WHENLASTRECEIVED AS DATE) AS WHENLASTRECEIVED,

    -- Audit
    _FIVETRAN_DELETED AS _FIVETRAN_DELETED,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE

FROM source_data

)

select *
from cleaned
