{% set company = var('company', 'unknown_company') | lower %}
{% set sourcesystem = var('sourcesystem', 'unknown_source') | lower %}
{{ config(enabled = var('sourcesystem', 'none') == 'sage') }}

{{ config(
    database = get_target_database(company),
    materialized = 'incremental',
    incremental_strategy = 'merge',
    unique_key = 'EMPLOYEEID'
) }}

with source_data as (
    select *
    from {{ get_raw_source(company, sourcesystem, 'EMPLOYEE') }}
    {% if is_incremental() %}
    where CAST(WHENMODIFIED AS TIMESTAMP_NTZ) > (
        select coalesce(max(WHENMODIFIED), '1900-01-01'::timestamp_ntz)
        from {{ this }}
    )
    or _FIVETRAN_DELETED = true
    {% endif %}
),

cleaned as (
    SELECT
    -- Primary Key
    TRIM(EMPLOYEEID) AS EMPLOYEEID,

    -- Core Identifiers
    TRY_CAST(RECORDNO AS INT) AS RECORDNO,
    TRIM(STATUS) AS STATUS,
    TRIM(TITLE) AS TITLE,

    -- Contact Info
    INITCAP(TRIM(CONTACT_NAME)) AS CONTACT_NAME,
    TRY_CAST(CONTACTKEY AS INT) AS CONTACTKEY,

    -- Personal Info
    TRIM(PERSONALINFO_COMPANYNAME) AS PERSONALINFO_COMPANYNAME,
    TRIM(PERSONALINFO_CONTACTNAME) AS PERSONALINFO_CONTACTNAME,

    -- Supervisor
    TRIM(SUPERVISORID) AS SUPERVISORID,
    INITCAP(TRIM(SUPERVISORNAME)) AS SUPERVISORNAME,

    -- Name & Contact
    TRIM(PERSONALINFO_FIRSTNAME) AS PERSONALINFO_FIRSTNAME,
    TRIM(PERSONALINFO_LASTNAME) AS PERSONALINFO_LASTNAME,
    TRIM(PERSONALINFO_INITIAL) AS PERSONALINFO_INITIAL,
    TRIM(PERSONALINFO_EMAIL_1) AS PERSONALINFO_EMAIL_1,
    TRIM(PERSONALINFO_PHONE_1) AS PERSONALINFO_PHONE_1,
    TRIM(PERSONALINFO_PRINTAS) AS PERSONALINFO_PRINTAS,
    TRIM(PERSONALINFO_MAILADDRESS_COUNTRY) AS PERSONALINFO_MAILADDRESS_COUNTRY,
    TRIM(PERSONALINFO_MAILADDRESS_COUNTRYCODE) AS PERSONALINFO_MAILADDRESS_COUNTRYCODE,

    -- Department
    TRIM(DEPARTMENTID) AS DEPARTMENTID,
    TRY_CAST(DEPARTMENTKEY AS INT) AS DEPARTMENTKEY,

    -- Location
    TRIM(LOCATIONID) AS LOCATIONID,
    TRY_CAST(LOCATIONKEY AS INT) AS LOCATIONKEY,

    -- Employee Type
    TRIM(EMPLOYEETYPE) AS EMPLOYEETYPE,
    TRY_CAST(EMPTYPEKEY AS INT) AS EMPTYPEKEY,

    -- Entity
    TRIM(ENTITY) AS ENTITY,
    TRIM(MEGAENTITYID) AS MEGAENTITYID,
    TRY_CAST(MEGAENTITYKEY AS INT) AS MEGAENTITYKEY,
    TRIM(MEGAENTITYNAME) AS MEGAENTITYNAME,

    -- Flags
    CAST(GENERIC AS BOOLEAN) AS GENERIC,
    CAST(MERGEPAYMENTREQ AS BOOLEAN) AS MERGEPAYMENTREQ,
    CAST(PAYMENTNOTIFY AS BOOLEAN) AS PAYMENTNOTIFY,
    CAST(POSTACTUALCOST AS BOOLEAN) AS POSTACTUALCOST,

    -- Relationships
    TRY_CAST(CREATEDBY AS INT) AS CREATEDBY,
    TRY_CAST(MODIFIEDBY AS INT) AS MODIFIEDBY,
    TRY_CAST(PARENTKEY AS INT) AS PARENTKEY,

    -- Services
    TRIM(FILEPAYMENTSERVICE) AS FILEPAYMENTSERVICE,

    -- Dates
    CAST(WHENCREATED AS TIMESTAMP_NTZ) AS WHENCREATED,
    CAST(WHENMODIFIED AS TIMESTAMP_NTZ) AS WHENMODIFIED,

    -- Audit
    _FIVETRAN_DELETED AS _FIVETRAN_DELETED,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE
FROM source_data

)

select *
from cleaned
