{% set company = var('company', 'Unknown company') | lower %}
{% set sourcesystem = var('sourcesystem', 'Unknown source') | lower %}
{{ config(enabled = var('sourcesystem', 'none') == 'sage') }}

{{ config(
    database = get_target_database(company),
    materialized = 'incremental',
    incremental_strategy = 'merge',
    unique_key = 'LOCATIONID'
) }}

with source_data as (

    select *
    from {{ get_raw_source(company, sourcesystem, 'LOCATION') }}
    
    {% if is_incremental() %}
        where WHENMODIFIED > (
            select coalesce(max(WHENMODIFIED), '1900-01-01'::timestamp_ntz)
            from {{ this }}
        )
        or _FIVETRAN_DELETED = true
    {% endif %}

),

cleaned as (

    SELECT
    -- Primary Key
    TRIM(LOCATIONID) AS LOCATIONID,

    -- Core Identifiers
    TRY_CAST(RECORDNO AS INT) AS RECORDNO,
    TRIM(NAME) AS NAME,
    TRIM(ENTITY) AS ENTITY,
    TRIM(STATUS) AS STATUS,
    TRIM(LOCATIONTYPE) AS LOCATIONTYPE,
    TRIM(MODEL_TYPE) AS MODEL_TYPE,
    TRIM(PROJECT_TYPE) AS PROJECT_TYPE,
    TRIM(SITE_TYPE) AS SITE_TYPE,
    TRIM(SITE_STATUS) AS SITE_STATUS,
    TRIM(STAGE) AS STAGE,
    TRIM(REVENUE_STREAM) AS REVENUE_STREAM,
    TRY_CAST(SORT_ORDER AS INT) AS SORT_ORDER,

    -- Contact Info
    TRIM(CONTACTINFO_CONTACTNAME) AS CONTACTINFO_CONTACTNAME,
    TRIM(CONTACTINFO_FIRSTNAME) AS CONTACTINFO_FIRSTNAME,
    TRIM(CONTACTINFO_LASTNAME) AS CONTACTINFO_LASTNAME,
    TRIM(CONTACTINFO_PRINTAS) AS CONTACTINFO_PRINTAS,
    TRY_CAST(CONTACTKEY AS INT) AS CONTACTKEY,

    -- Contact Address
    TRIM(CONTACTINFO_MAILADDRESS_ADDRESS_1) AS CONTACTINFO_MAILADDRESS_ADDRESS_1,
    TRIM(CONTACTINFO_MAILADDRESS_CITY) AS CONTACTINFO_MAILADDRESS_CITY,
    TRIM(CONTACTINFO_MAILADDRESS_STATE) AS CONTACTINFO_MAILADDRESS_STATE,
    TRIM(CONTACTINFO_MAILADDRESS_COUNTRY) AS CONTACTINFO_MAILADDRESS_COUNTRY,
    TRIM(CONTACTINFO_MAILADDRESS_COUNTRYCODE) AS CONTACTINFO_MAILADDRESS_COUNTRYCODE,
    TRIM(CONTACTINFO_MAILADDRESS_ZIP) AS CONTACTINFO_MAILADDRESS_ZIP,

    -- Accounting & Legal
    TRIM(FEDERALID) AS FEDERALID,
    TRIM(CUSTTITLE) AS CUSTTITLE,
    TRIM(REPORTPRINTAS) AS REPORTPRINTAS,
    TRIM(TAXID) AS TAXID,

    -- Dates
    CAST(CLOSE_DATE AS DATE) AS CLOSE_DATE,
    CAST(STARTDATE AS DATE) AS STARTDATE,
    CAST(LOCATION_OPEN_DATE AS DATE) AS LOCATION_OPEN_DATE,
    CAST(LOCATION_COHORT_OPEN_DATE AS DATE) AS LOCATION_COHORT_OPEN_DATE,
    CAST(WHENCREATED AS TIMESTAMP_NTZ) AS WHENCREATED,
    CAST(WHENMODIFIED AS TIMESTAMP_NTZ) AS WHENMODIFIED,

    -- Flags
    CAST(HAS_IE_RELATION AS BOOLEAN) AS HAS_IE_RELATION,
    CAST(ISROOT AS BOOLEAN) AS ISROOT,

    -- Misc
    TRIM(ADDRESSCOUNTRYDEFAULT) AS ADDRESSCOUNTRYDEFAULT,
    TRIM(BUSINESSDAYS) AS BUSINESSDAYS,
    TRIM(WEEKENDS) AS WEEKENDS,
    TRIM(DISTRICT_MANAGER) AS DISTRICT_MANAGER,
    TRIM(CPM) AS CPM,
    TRY_CAST(FIRSTMONTH AS INT) AS FIRSTMONTH,
    TRY_CAST(FIRSTMONTHTAX AS INT) AS FIRSTMONTHTAX,

    -- Relationships
    TRIM(PARENTID) AS PARENTID,
    TRIM(PARENTNAME) AS PARENTNAME,
    TRY_CAST(PARENTKEY AS INT) AS PARENTKEY,
    TRY_CAST(CREATEDBY AS INT) AS CREATEDBY,
    TRY_CAST(MODIFIEDBY AS INT) AS MODIFIEDBY,
    TRIM(CREATEDBYLOGINID) AS CREATEDBYLOGINID,
    TRIM(MODIFIEDBYLOGINID) AS MODIFIEDBYLOGINID,

    -- Audit
    _FIVETRAN_DELETED AS _FIVETRAN_DELETED,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE

FROM source_data

)

select * from cleaned
