{% set company = var('company', 'unknown_company') | lower %}
{% set sourcesystem = var('sourcesystem', 'unknown_source') | lower %}
{{ config(enabled = var('sourcesystem', 'none') == 'sage') }}

{{ config(
    database = get_target_database(company),
    materialized = 'incremental',
    incremental_strategy = 'merge',
    unique_key = 'BATCH_NO'
) }}

with source_data as (
    select *
    from {{ get_raw_source(company, sourcesystem, 'GL_BATCH') }}
    {% if is_incremental() %}
    where cast(WHENMODIFIED as timestamp_ntz) > (
        select coalesce(max(WHEN_MODIFIED), '1900-01-01'::timestamp_ntz)
        from {{ this }}
    )
    or _FIVETRAN_DELETED = true
    {% endif %}
),

cleaned as (
    SELECT
    -- Primary Key
    TRY_CAST(BATCHNO AS INT) AS BATCHNO,

    -- Core Identifiers
    TRY_CAST(RECORDNO AS INT) AS RECORDNO,
    TRIM(BATCH_TITLE) AS BATCH_TITLE,
    TRY_CAST(BASELOCATION AS INT) AS BASELOCATION,
    TRIM(BASELOCATION_NO) AS BASELOCATION_NO,
    TRIM(JOURNAL) AS JOURNAL,
    TRIM(MODULE) AS MODULE,
    TRIM(STATE) AS STATE,
    TRIM(TAXIMPLICATIONS) AS TAXIMPLICATIONS,
    TRIM(TRANSACTIONSOURCE) AS TRANSACTIONSOURCE,

    -- Entity Info
    TRIM(MEGAENTITYID) AS MEGAENTITYID,
    TRY_CAST(MEGAENTITYKEY AS INT) AS MEGAENTITYKEY,
    TRIM(MEGAENTITYNAME) AS MEGAENTITYNAME,

    -- References
    TRIM(REFERENCENO) AS REFERENCENO,
    TRIM(RECORD_URL) AS RECORD_URL,
    TRY_CAST(PRBATCHKEY AS INT) AS PRBATCHKEY,
    TRY_CAST(REVERSEDKEY AS INT) AS REVERSEDKEY,
    TRY_CAST(RFIXED_ASSETS_LOG AS INT) AS RFIXED_ASSETS_LOG,
    TRY_CAST(RDEPRECIATION_SCHEDULE AS INT) AS RDEPRECIATION_SCHEDULE,
    TRY_CAST(RPESENTRY AS INT) AS RPESENTRY,
    TRY_CAST(SCHOPKEY AS INT) AS SCHOPKEY,
    TRY_CAST(SUPDOCKEY AS INT) AS SUPDOCKEY,
    TRIM(SUPDOCID) AS SUPDOCID,
    TRY_CAST(USERKEY AS INT) AS USERKEY,
    TRIM(USERINFO_LOGINID) AS USERINFO_LOGINID,

    -- Flags
    CAST(STATISTICAL AS BOOLEAN) AS STATISTICAL,

    -- Dates
    CAST(BATCH_DATE AS DATE) AS BATCH_DATE,
    CAST(REVERSED AS DATE) AS REVERSED,
    CAST(REVERSEDFROM AS DATE) AS REVERSEDFROM,

    -- Audit
    TRY_CAST(CREATEDBY AS INT) AS CREATEDBY,
    TRIM(CREATEDBYLOGINID) AS CREATEDBYLOGINID,
    TRY_CAST(MODIFIEDBY AS INT) AS MODIFIEDBY,
    TRIM(MODIFIEDBYID) AS MODIFIEDBYID,
    TRIM(MODIFIEDBYLOGINID) AS MODIFIEDBYLOGINID,
    CAST(WHENCREATED AS TIMESTAMP_NTZ) AS WHENCREATED,
    CAST(WHENMODIFIED AS TIMESTAMP_NTZ) AS WHENMODIFIED,
    CAST(MODIFIED AS TIMESTAMP_NTZ) AS MODIFIED,

    _FIVETRAN_DELETED AS _FIVETRAN_DELETED,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SILVER_LOAD_DATE
FROM source_data

)

select *
from cleaned
